# Generated by Django 3.0.7 on 2023-07-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('level_itmid', models.AutoField(db_column='LEVEL_ItmID', primary_key=True, serialize=False)),
                ('level_name', models.CharField(blank=True, db_column='LEVEL_Name', max_length=40, null=True)),
                ('level_description', models.CharField(blank=True, db_column='LEVEL_Description', max_length=60, null=True)),
                ('level_permitappointment', models.BooleanField(db_column='LEVEL_PermitAppointment', default=False)),
                ('level_permitcrm', models.BooleanField(db_column='LEVEL_PermitCrm', default=False)),
                ('level_permitcreditor', models.BooleanField(db_column='LEVEL_PermitCreditor', default=False)),
                ('level_permitstaff', models.BooleanField(db_column='LEVEL_PermitStaff', default=False)),
                ('level_permituserlogin', models.BooleanField(db_column='LEVEL_PermitUserLogin', default=False)),
                ('level_permitstockitem', models.BooleanField(db_column='LEVEL_PermitStockItem', default=False)),
                ('level_permitsecurity', models.BooleanField(db_column='LEVEL_PermitSecurity', default=False)),
                ('level_permitsendmail', models.BooleanField(db_column='LEVEL_PermitSendmail', default=False)),
                ('level_permitinventory', models.BooleanField(db_column='LEVEL_PermitInventory', default=False)),
                ('level_permitanalysis', models.BooleanField(db_column='LEVEL_PermitAnalysis', default=False)),
                ('level_permitmaintain', models.BooleanField(db_column='LEVEL_PermitMaintain', default=False)),
                ('level_permitpos', models.BooleanField(db_column='LEVEL_PermitPOS', default=False)),
                ('level_isactive', models.BooleanField(db_column='LEVEL_Isactive', default=True)),
                ('level_permitpaytable', models.BooleanField(db_column='LEVEL_PermitPaytable', default=False)),
                ('level_permitforex', models.BooleanField(db_column='LEVEL_PermitForex', default=False)),
                ('level_permitdiv', models.BooleanField(db_column='LEVEL_PermitDiv', default=False)),
                ('level_permitdiscount', models.BooleanField(db_column='LEVEL_PermitDiscount', default=False)),
                ('level_permitdept', models.BooleanField(db_column='LEVEL_PermitDept', default=False)),
                ('level_permitclass', models.BooleanField(db_column='LEVEL_PermitClass', default=False)),
                ('level_permitpromo', models.BooleanField(db_column='LEVEL_PermitPromo', default=False)),
                ('level_permitattendance', models.BooleanField(db_column='LEVEL_PermitAttendance', default=False)),
                ('level_permitstkreceive', models.BooleanField(db_column='LEVEL_PermitStkReceive', default=False)),
                ('level_permitstkadj', models.BooleanField(db_column='LEVEL_PermitStkAdj', default=False)),
                ('level_permitstktrans', models.BooleanField(db_column='LEVEL_PermitStkTrans', default=False)),
                ('level_permitstkwriteoff', models.BooleanField(db_column='LEVEL_PermitStkWriteOff', default=False)),
                ('level_permitstkquery', models.BooleanField(db_column='LEVEL_PermitStkQuery', default=False)),
                ('level_permitstktk', models.BooleanField(db_column='LEVEL_PermitStkTK', default=False)),
                ('level_permitstkvar', models.BooleanField(db_column='LEVEL_PermitStkVar', default=False)),
                ('level_code', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('role_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'Securities',
            },
        ),
    ]
