# Generated by Django 3.0.7 on 2023-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDiv',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_isactive', models.BooleanField(default=True)),
                ('itm_seq', models.IntegerField(db_column='ITM_SEQ', null=True)),
                ('status_code', models.CharField(blank=True, db_column='Status_Code', max_length=10, null=True)),
                ('process_remark', models.CharField(blank=True, db_column='Process_Remark', max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('pay_color', models.CharField(blank=True, max_length=255, null=True)),
                ('issellable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Item_Div',
            },
        ),
    ]
