# Generated by Django 3.0.7 on 2023-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0005_itemdiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDept',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_status', models.BooleanField(default=True)),
                ('itm_seq', models.IntegerField(blank=True, db_column='ITM_SEQ', null=True)),
                ('allowcashsales', models.BooleanField(db_column='AllowCashSales', null=True)),
                ('itm_showonsales', models.BooleanField(db_column='ITM_ShowOnSales', null=True)),
                ('isfirsttrial', models.BooleanField(blank=True, db_column='IsFirstTrial', null=True)),
                ('is_voucher', models.BooleanField(db_column='Is_Voucher', null=True)),
                ('is_prepaid', models.BooleanField(db_column='Is_Prepaid', null=True)),
                ('is_package', models.BooleanField(db_column='Is_Package', null=True)),
                ('is_retailproduct', models.BooleanField(db_column='Is_RetailProduct', null=True)),
                ('is_salonproduct', models.BooleanField(db_column='Is_SalonProduct', null=True)),
                ('validity_period', models.IntegerField(blank=True, db_column='Validity_Period', null=True)),
                ('is_service', models.BooleanField(db_column='Is_Service', null=True)),
                ('dept_pic_b', models.BinaryField(blank=True, db_column='Dept_PIC_B', null=True)),
                ('is_compound', models.BooleanField(db_column='Is_Compound', null=True)),
                ('dept_pic', models.CharField(blank=True, db_column='Dept_PIC', max_length=100, null=True)),
                ('vilidity_from_date', models.DateTimeField(blank=True, db_column='Vilidity_From_Date', null=True)),
                ('vilidity_to_date', models.DateTimeField(blank=True, db_column='Vilidity_To_date', null=True)),
                ('vilidity_from_time', models.DateTimeField(blank=True, db_column='Vilidity_From_Time', null=True)),
                ('vilidity_to_time', models.DateTimeField(blank=True, db_column='Vilidity_To_Time', null=True)),
                ('process_remark', models.CharField(blank=True, db_column='Process_Remark', max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deptpic', models.ImageField(null=True, upload_to='img')),
                ('pay_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Item_Dept',
            },
        ),
    ]
