# Generated by Django 3.0.7 on 2023-07-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0006_itemdept'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClass',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_isactive', models.BooleanField(default=True)),
                ('itm_seq', models.IntegerField(blank=True, db_column='ITM_SEQ', null=True)),
                ('process_remark', models.CharField(blank=True, db_column='Process_Remark', max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'item_Class',
            },
        ),
        migrations.CreateModel(
            name='ItemRange',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('itm_status', models.BooleanField(blank=True, default=True, null=True)),
                ('itm_seq', models.IntegerField(blank=True, db_column='itm_SEQ', null=True)),
                ('itm_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('itm_dept', models.CharField(blank=True, db_column='itm_Dept', max_length=10, null=True)),
                ('isproduct', models.BooleanField(db_column='isProduct', null=True)),
                ('pic_path', models.CharField(blank=True, db_column='PIC_Path', max_length=255, null=True)),
                ('prepaid_for_product', models.BooleanField(db_column='Prepaid_For_Product', null=True)),
                ('prepaid_for_service', models.BooleanField(db_column='Prepaid_For_Service', null=True)),
                ('prepaid_for_all', models.BooleanField(db_column='Prepaid_For_All', null=True)),
                ('isservice', models.BooleanField(db_column='IsService', null=True)),
                ('isvoucher', models.BooleanField(db_column='IsVoucher', null=True)),
                ('isprepaid', models.BooleanField(db_column='IsPrepaid', null=True)),
                ('iscompound', models.BooleanField(db_column='IsCompound', null=True)),
                ('process_remark', models.CharField(blank=True, db_column='Process_Remark', max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('itm_Deptid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.ItemDept')),
            ],
            options={
                'db_table': 'Item_Range',
            },
        ),
    ]
