# Generated by Django 3.0.7 on 2023-07-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0007_itemclass_itemrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('color_id', models.AutoField(db_column='Color_ID', primary_key=True, serialize=False)),
                ('color_code', models.CharField(blank=True, db_column='Color_Code', max_length=10, null=True)),
                ('color_desc', models.CharField(blank=True, db_column='Color_Desc', max_length=50, null=True)),
                ('color_shortdesc', models.CharField(blank=True, db_column='Color_ShortDesc', max_length=10, null=True)),
                ('color_user', models.CharField(blank=True, db_column='Color_User', max_length=50, null=True)),
                ('color_date', models.DateTimeField(blank=True, db_column='Color_Date', null=True)),
                ('color_time', models.DateTimeField(blank=True, db_column='Color_Time', null=True)),
                ('color_isactive', models.BooleanField(db_column='Color_Isactive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Item_Color',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_name', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_removable', models.BooleanField(db_column='ITM_REMOVABLE', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'item_type',
            },
        ),
    ]
