# Generated by Django 3.0.7 on 2023-07-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0008_itemcolor_itemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('size_id', models.AutoField(db_column='Size_ID', primary_key=True, serialize=False)),
                ('sizepack_code', models.CharField(blank=True, db_column='SizePack_Code', max_length=10, null=True)),
                ('size_code', models.CharField(blank=True, db_column='Size_Code', max_length=6, null=True)),
                ('size_desc', models.CharField(blank=True, db_column='Size_Desc', max_length=50, null=True)),
                ('size_shortdesc', models.CharField(blank=True, db_column='Size_ShortDesc', max_length=10, null=True)),
                ('size_unit', models.CharField(blank=True, db_column='Size_Unit', max_length=50, null=True)),
                ('size_width', models.CharField(blank=True, db_column='Size_Width', max_length=50, null=True)),
                ('size_height', models.CharField(blank=True, db_column='Size_Height', max_length=50, null=True)),
                ('size_tickness', models.CharField(blank=True, db_column='Size_Tickness', max_length=50, null=True)),
                ('size_lenght', models.CharField(blank=True, db_column='Size_Lenght', max_length=50, null=True)),
                ('size_user', models.CharField(blank=True, db_column='Size_User', max_length=50, null=True)),
                ('size_date', models.DateTimeField(blank=True, db_column='Size_Date', null=True)),
                ('size_time', models.DateTimeField(blank=True, db_column='Size_Time', null=True)),
                ('size_isactive', models.BooleanField(db_column='Size_Isactive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Item_Size',
            },
        ),
        migrations.CreateModel(
            name='ItemSizepack',
            fields=[
                ('sizepack_id', models.AutoField(db_column='SizePack_ID', primary_key=True, serialize=False)),
                ('sizepack_code', models.CharField(blank=True, db_column='SizePack_Code', max_length=10, null=True)),
                ('sizepack_desc', models.CharField(blank=True, db_column='SizePack_Desc', max_length=50, null=True)),
                ('sizepack_shortdesc', models.CharField(blank=True, db_column='SizePack_ShortDesc', max_length=10, null=True)),
                ('sizepack_user', models.CharField(blank=True, db_column='SizePack_User', max_length=50, null=True)),
                ('sizepack_date', models.DateTimeField(blank=True, db_column='SizePack_Date', null=True)),
                ('sizepack_time', models.DateTimeField(blank=True, db_column='SizePack_Time', null=True)),
                ('sizepack_isactive', models.BooleanField(db_column='SizePack_Isactive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Item_SizePack',
            },
        ),
    ]
