# Generated by Django 3.0.7 on 2023-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0010_itemfabric_itemseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_status', models.BooleanField(default=True)),
                ('itm_seq', models.IntegerField(blank=True, db_column='ITM_SEQ', null=True)),
                ('pic_path', models.CharField(blank=True, db_column='PIC_PATH', max_length=256, null=True)),
                ('voucher_for_sales', models.BooleanField(db_column='Voucher_For_Sales', null=True)),
                ('voucher_brand', models.BooleanField(db_column='Voucher_Brand', null=True)),
                ('retail_product_brand', models.BooleanField(db_column='Retail_Product_Brand', null=True)),
                ('prepaid_brand', models.BooleanField(db_column='Prepaid_Brand', null=True)),
                ('process_remark', models.CharField(blank=True, db_column='Process_Remark', max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Item_Brand',
            },
        ),
    ]
