# Generated by Django 3.0.7 on 2023-07-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0002_itemsitelist'),
        ('cl_table', '0012_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance2',
            fields=[
                ('attn_id', models.AutoField(db_column='Attn_ID', primary_key=True, serialize=False)),
                ('attn_emp_code', models.CharField(blank=True, db_column='Attn_Emp_code', max_length=50, null=True)),
                ('attn_site_code', models.CharField(blank=True, db_column='Attn_Site_Code', max_length=50, null=True)),
                ('attn_macno', models.CharField(blank=True, db_column='Attn_MacNo', max_length=50, null=True)),
                ('attn_type', models.CharField(blank=True, db_column='Attn_Type', max_length=50, null=True)),
                ('attn_date', models.DateTimeField(auto_now_add=True, db_column='Attn_Date', null=True)),
                ('attn_time', models.DateTimeField(auto_now_add=True, db_column='Attn_Time', null=True)),
                ('attn_remark', models.CharField(blank=True, db_column='Attn_Remark', max_length=50, null=True)),
                ('attn_mov_in', models.IntegerField(db_column='Attn_Mov_In', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='Create_date', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='Create_time', null=True)),
                ('missing_clock', models.BooleanField(db_column='Missing_Clock', null=True)),
                ('verify_code', models.CharField(blank=True, db_column='Verify_Code', max_length=50, null=True)),
                ('verify_name', models.CharField(blank=True, db_column='Verify_Name', max_length=50, null=True)),
                ('verify_reason', models.CharField(blank=True, db_column='Verify_Reason', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Attn_Emp_codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
                ('Attn_Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'Attendance2',
            },
        ),
    ]
