# Generated by Django 3.0.7 on 2023-07-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0013_attendance2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='cl_table.Attendance2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, to='cl_table.Stock'),
        ),
    ]
