# Generated by Django 3.0.7 on 2023-07-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0014_auto_20230717_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmspw',
            name='Emp_Codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee'),
        ),
    ]
