# Generated by Django 3.0.7 on 2023-07-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0016_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUom',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('uom_code', models.CharField(blank=True, db_column='UOM_Code', max_length=20, null=True)),
                ('uom_desc', models.CharField(blank=True, db_column='UOM_Desc', max_length=50, null=True)),
                ('uom_user', models.CharField(blank=True, db_column='UOM_User', max_length=20, null=True)),
                ('uom_date', models.DateTimeField(blank=True, db_column='UOM_Date', null=True)),
                ('uom_time', models.DateTimeField(blank=True, db_column='UOM_Time', null=True)),
                ('uom_isactive', models.BooleanField(blank=True, db_column='UOM_Isactive', default=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Item_UOM',
            },
        ),
    ]
