# Generated by Django 3.0.7 on 2023-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0017_itemuom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptType',
            fields=[
                ('appt_type_id', models.AutoField(db_column='Appt_type_id', primary_key=True, serialize=False)),
                ('appt_type_desc', models.CharField(blank=True, db_column='Appt_type_desc', max_length=50, null=True)),
                ('appt_type_code', models.CharField(blank=True, db_column='Appt_type_code', max_length=50, null=True)),
                ('appt_type_isactive', models.BooleanField(db_column='Appt_type_Isactive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Appt_Type',
            },
        ),
    ]
