# Generated by Django 3.0.7 on 2023-07-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0020_treatment_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentAccount',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cust_code', models.CharField(db_column='Cust_Code', max_length=20, null=True)),
                ('sa_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('ref_no', models.CharField(db_column='Ref_No', max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Top Up', 'Top Up'), ('Sales', 'Sales')], db_column='Type', max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('balance', models.FloatField(db_column='Balance', null=True)),
                ('user_name', models.CharField(blank=True, db_column='User_Name', max_length=50, null=True)),
                ('sa_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('ref_transacno', models.CharField(blank=True, db_column='Ref_Transacno', max_length=20, null=True)),
                ('sa_transacno', models.CharField(max_length=20, null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('outstanding', models.FloatField(blank=True, db_column='Outstanding', null=True)),
                ('deposit', models.FloatField(blank=True, db_column='Deposit', null=True)),
                ('treatment_parentcode', models.CharField(blank=True, db_column='Treatment_ParentCode', max_length=20, null=True)),
                ('sa_status', models.CharField(blank=True, choices=[('SA', 'SA'), ('VOID', 'VOID'), ('SU', 'SU')], max_length=5, null=True)),
                ('cas_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sa_staffno', models.CharField(max_length=100, null=True)),
                ('sa_staffname', models.CharField(blank=True, max_length=600, null=True)),
                ('dt_lineno', models.IntegerField(db_column='dt_LineNo', null=True)),
                ('package_code', models.CharField(blank=True, db_column='Package_Code', max_length=50, null=True)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=50, null=True)),
                ('Cust_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
                ('User_Nameid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'Treatment_Account',
            },
        ),
    ]
