# Generated by Django 3.0.7 on 2023-07-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0026_tmptreatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocReason',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('foc_reason_code', models.CharField(db_column='FOC_Reason_Code', max_length=20, null=True)),
                ('foc_reason_sdesc', models.CharField(blank=True, db_column='FOC_Reason_SDesc', max_length=20, null=True)),
                ('foc_reason_ldesc', models.CharField(blank=True, db_column='FOC_Reason_LDesc', max_length=20, null=True)),
                ('foc_reason_isactive', models.BooleanField(db_column='FOC_Reason_IsActive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'FOC_Reason',
            },
        ),
    ]
