# Generated by Django 3.0.7 on 2023-07-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_itemcart'),
        ('cl_table', '0028_tmptreatment_itemcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentaccount',
            name='itemcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
    ]
