# Generated by Django 3.0.7 on 2023-07-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_pospackagedeposit'),
        ('cl_table', '0029_treatmentaccount_itemcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpitemhelper',
            name='itemcart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
        migrations.AddField(
            model_name='tmpitemhelper',
            name='tmptreatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Tmptreatment'),
        ),
        migrations.AddField(
            model_name='tmpitemhelper',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Treatment'),
        ),
    ]
