# Generated by Django 3.0.7 on 2023-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0030_auto_20230717_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Securitycontrollist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('controlname', models.CharField(blank=True, db_column='ControlName', max_length=50, null=True)),
                ('controldesc', models.CharField(blank=True, db_column='ControlDesc', max_length=50, null=True)),
                ('controlindex', models.IntegerField(blank=True, db_column='ControlIndex', null=True)),
                ('controlparent', models.CharField(blank=True, db_column='ControlParent', max_length=50, null=True)),
                ('control_status', models.BooleanField(blank=True, db_column='Control_Status', null=True)),
                ('seq', models.IntegerField(blank=True, db_column='SEQ', null=True)),
            ],
            options={
                'db_table': 'SecurityControlList',
            },
        ),
        migrations.CreateModel(
            name='Securitylevellist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('controlname', models.CharField(blank=True, db_column='ControlName', max_length=50, null=True)),
                ('controldesc', models.CharField(blank=True, db_column='ControlDesc', max_length=50, null=True)),
                ('controlparent', models.CharField(blank=True, db_column='ControlParent', max_length=50, null=True)),
                ('controlindex', models.IntegerField(blank=True, db_column='ControlIndex', null=True)),
                ('controlstatus', models.BooleanField(db_column='ControlStatus')),
                ('level_itemid', models.CharField(blank=True, db_column='Level_ItemID', max_length=50, null=True)),
                ('seq', models.CharField(blank=True, db_column='SEQ', max_length=10, null=True)),
            ],
            options={
                'db_table': 'SecurityLevelList',
            },
        ),
    ]
