# Generated by Django 3.0.7 on 2023-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0035_creditnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseHdr',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('reverse_no', models.CharField(blank=True, db_column='Reverse_No', max_length=50, null=True)),
                ('reverse_date', models.DateTimeField(auto_now_add=True, db_column='Reverse_Date', null=True)),
                ('reverse_time', models.DateTimeField(auto_now_add=True, db_column='Reverse_Time', null=True)),
                ('staff_code', models.CharField(blank=True, db_column='Staff_Code', max_length=50, null=True)),
                ('staff_name', models.CharField(blank=True, db_column='Staff_Name', max_length=50, null=True)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=50, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=50, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('has_adjustment', models.BooleanField(blank=True, db_column='Has_Adjustment', null=True)),
                ('adjustment_value', models.FloatField(blank=True, db_column='Adjustment_Value', null=True)),
                ('credit_note_amt', models.FloatField(blank=True, db_column='Credit_Note_Amt', null=True)),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=50, null=True)),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=50, null=True)),
                ('total_balance', models.FloatField(blank=True, db_column='Total_Balance', null=True)),
                ('ref_creditnote', models.CharField(blank=True, db_column='Ref_CreditNote', max_length=20, null=True)),
                ('reason1', models.CharField(blank=True, db_column='Reason1', max_length=50, null=True)),
                ('reason2', models.CharField(blank=True, db_column='Reason2', max_length=50, null=True)),
                ('reason3', models.CharField(blank=True, db_column='Reason3', max_length=50, null=True)),
                ('reason4', models.CharField(blank=True, db_column='Reason4', max_length=50, null=True)),
                ('reason_adj_value1', models.FloatField(blank=True, db_column='Reason_Adj_Value1', null=True)),
                ('reason_adj_value2', models.FloatField(blank=True, db_column='Reason_Adj_Value2', null=True)),
                ('reason_adj_value3', models.FloatField(blank=True, db_column='Reason_Adj_Value3', null=True)),
                ('reason_adj_value4', models.FloatField(blank=True, db_column='Reason_Adj_Value4', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Reverse_Hdr',
            },
        ),
    ]
