# Generated by Django 3.0.7 on 2023-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0036_reversehdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseDtl',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('treatment_no', models.CharField(blank=True, db_column='Treatment_No', max_length=50, null=True)),
                ('treatment_desc', models.CharField(blank=True, db_column='Treatment_Desc', max_length=250, null=True)),
                ('treatment_price', models.FloatField(blank=True, db_column='Treatment_Price', null=True)),
                ('transac_no', models.CharField(blank=True, db_column='Transac_No', max_length=50, null=True)),
                ('reverse_no', models.CharField(blank=True, db_column='Reverse_No', max_length=50, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Reverse_Dtl',
            },
        ),
    ]
