# Generated by Django 3.0.7 on 2023-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0037_reversedtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnRefund',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rfn_trans_no', models.CharField(blank=True, db_column='RFN_Trans_No', max_length=20, null=True)),
                ('cn_no', models.CharField(blank=True, db_column='CN_No', max_length=20, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('staff_code', models.CharField(blank=True, db_column='Staff_Code', max_length=20, null=True)),
                ('transac_no', models.CharField(blank=True, db_column='Transac_No', max_length=20, null=True)),
                ('rfn_date', models.DateTimeField(blank=True, db_column='RFN_Date', null=True)),
                ('rfn_before_amt', models.FloatField(blank=True, db_column='RFN_Before_Amt', null=True)),
                ('rfn_adjust_amt', models.FloatField(blank=True, db_column='RFN_Adjust_Amt', null=True)),
                ('rfn_new_amt', models.FloatField(blank=True, db_column='RFN_New_Amt', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'CN_Refund',
            },
        ),
    ]
