# Generated by Django 3.0.7 on 2023-07-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0038_cnrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidAccount',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pp_no', models.CharField(db_column='PP_NO', max_length=50, null=True)),
                ('pp_type', models.CharField(db_column='PP_TYPE', max_length=50, null=True)),
                ('pp_desc', models.CharField(blank=True, db_column='PP_DESC', max_length=250, null=True)),
                ('sa_date', models.DateTimeField(auto_now_add=True, db_column='SA_DATE', null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, db_column='START_DATE', null=True)),
                ('exp_date', models.DateTimeField(blank=True, db_column='EXP_DATE', null=True)),
                ('cust_code', models.CharField(blank=True, db_column='CUST_CODE', max_length=50, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='CUST_NAME', max_length=50, null=True)),
                ('pp_amt', models.FloatField(blank=True, db_column='PP_AMT', null=True)),
                ('pp_bonus', models.FloatField(blank=True, db_column='PP_BONUS', null=True)),
                ('pp_total', models.FloatField(blank=True, db_column='PP_TOTAL', null=True)),
                ('transac_no', models.CharField(db_column='TRANSAC_NO', max_length=50)),
                ('item_no', models.CharField(db_column='ITEM_NO', max_length=50)),
                ('use_amt', models.FloatField(db_column='USE_AMT', null=True)),
                ('remain', models.FloatField(db_column='REMAIN', null=True)),
                ('ref1', models.CharField(blank=True, db_column='REF1', max_length=50, null=True)),
                ('ref2', models.CharField(blank=True, db_column='REF2', max_length=50, null=True)),
                ('status', models.BooleanField(db_column='STATUS', null=True)),
                ('site_code', models.CharField(db_column='SITE_CODE', max_length=50, null=True)),
                ('sa_status', models.CharField(blank=True, choices=[('DEPOSIT', 'DEPOSIT'), ('TOPUP', 'TOPUP'), ('SA', 'SA'), ('VT', 'VT')], db_column='SA_STATUS', max_length=50, null=True)),
                ('exp_status', models.BooleanField(db_column='EXP_STATUS', null=True)),
                ('voucher_no', models.CharField(blank=True, db_column='VOUCHER_NO', max_length=50, null=True)),
                ('isvoucher', models.BooleanField(db_column='ISVOUCHER', null=True)),
                ('has_deposit', models.BooleanField(db_column='HAS_DEPOSIT', null=True)),
                ('topup_amt', models.FloatField(blank=True, db_column='TopUp_AMT', null=True)),
                ('outstanding', models.FloatField(db_column='Outstanding', null=True)),
                ('active_deposit_bonus', models.BooleanField(db_column='Active_Deposit_Bonus', null=True)),
                ('topup_no', models.CharField(db_column='TopUp_No', max_length=50, null=True)),
                ('topup_date', models.DateTimeField(blank=True, db_column='TopUp_Date', null=True)),
                ('line_no', models.BigIntegerField(db_column='Line_No', null=True)),
                ('edit_date', models.DateTimeField(auto_now_add=True, db_column='Edit_Date', null=True)),
                ('cas_logno', models.CharField(blank=True, db_column='Cas_LogNo', max_length=50, null=True)),
                ('staff_name', models.CharField(blank=True, db_column='Staff_Name', max_length=50, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='Staff_No', max_length=50, null=True)),
                ('pp_type2', models.CharField(blank=True, db_column='PP_TYPE2', max_length=20, null=True)),
                ('condition_type1', models.CharField(blank=True, db_column='Condition_TYPE1', max_length=20, null=True)),
                ('pos_daud_lineno', models.IntegerField(blank=True, db_column='POS_DAUD_LineNo', null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
                ('lpackage', models.BooleanField(db_column='lPackage')),
                ('package_code', models.CharField(blank=True, db_column='Package_Code', max_length=50, null=True)),
                ('package_code_lineno', models.IntegerField(blank=True, db_column='Package_Code_LineNo', null=True)),
                ('prepaid_disc_type', models.CharField(blank=True, db_column='Prepaid_Disc_Type', max_length=20, null=True)),
                ('prepaid_disc_percent', models.FloatField(blank=True, db_column='Prepaid_Disc_Percent', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('item_code', models.CharField(blank=True, db_column='Item_Code', max_length=20, null=True)),
                ('terminate_prepaid', models.BooleanField(default=False)),
                ('Cust_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('Item_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock')),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'Prepaid_Account',
            },
        ),
    ]
