# Generated by Django 3.0.7 on 2023-07-17 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0044_customervoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosHaud',
            fields=[
                ('cas_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sa_transacno', models.CharField(max_length=20, null=True)),
                ('sa_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('sa_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('sa_status', models.CharField(blank=True, choices=[('SA', 'SA'), ('VT', 'VT'), ('SU', 'SU')], max_length=5, null=True)),
                ('sa_totamt', models.FloatField(blank=True, null=True)),
                ('sa_totqty', models.IntegerField(blank=True, db_column='sa_totQty', null=True)),
                ('sa_totdisc', models.FloatField(blank=True, null=True)),
                ('sa_totgst', models.FloatField(blank=True, null=True)),
                ('sa_staffno', models.CharField(blank=True, max_length=100, null=True)),
                ('sa_staffname', models.CharField(blank=True, max_length=600, null=True)),
                ('sa_custno', models.CharField(max_length=20, null=True)),
                ('sa_custname', models.CharField(blank=True, max_length=60, null=True)),
                ('sa_discuser', models.CharField(blank=True, db_column='sa_DiscUser', max_length=50, null=True)),
                ('sa_discamt', models.FloatField(blank=True, null=True)),
                ('sa_disctotal', models.FloatField(blank=True, db_column='sa_discTotal', null=True)),
                ('itemsite_code', models.CharField(db_column='ItemSite_Code', max_length=10, null=True)),
                ('sa_depositamt', models.FloatField(blank=True, db_column='sa_depositAmt', null=True)),
                ('isvoid', models.BooleanField(db_column='IsVoid', default=False, null=True)),
                ('void_refno', models.CharField(blank=True, db_column='Void_RefNo', max_length=20, null=True)),
                ('payment_remarks', models.CharField(blank=True, db_column='Payment_Remarks', max_length=100, null=True)),
                ('sa_transacamt', models.FloatField(blank=True, db_column='sa_TransacAmt', null=True)),
                ('holditemqty', models.IntegerField(db_column='HoldItemQty', null=True)),
                ('walkin', models.BooleanField(db_column='WalkIn', null=True)),
                ('sa_round', models.FloatField(blank=True, db_column='sa_Round', null=True)),
                ('total_outstanding', models.FloatField(blank=True, db_column='Total_Outstanding', null=True)),
                ('trans_user_login', models.CharField(blank=True, db_column='Trans_User_Login', max_length=20, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno_ref', models.CharField(blank=True, db_column='SA_TransacNo_Ref', max_length=20, null=True)),
                ('sa_transacno_type', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Redeem Service', 'Redeem Service'), ('Non Sales', 'Non Sales'), ('Void Transaction', 'Void Transaction')], db_column='SA_TransacNo_Type', max_length=20, null=True)),
                ('trans_remark', models.CharField(blank=True, db_column='Trans_Remark', max_length=200, null=True)),
                ('sa_transacno_title', models.CharField(blank=True, db_column='SA_TransacNo_Title', max_length=50, null=True)),
                ('issuestrans_user_login', models.CharField(blank=True, db_column='IssuesTrans_User_Login', max_length=20, null=True)),
                ('cart_id', models.CharField(max_length=20, null=True)),
                ('date_ofchoose_dress', models.DateField(blank=True, null=True)),
                ('date_ofphotoshooting', models.DateField(blank=True, null=True)),
                ('ItemSite_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
                ('sa_custnoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('sa_staffnoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
                ('trans_user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'pos_haud',
                'unique_together': {('sa_transacno', 'sa_custno', 'itemsite_code', 'sa_transacno_ref')},
            },
        ),
    ]
