# Generated by Django 3.0.7 on 2023-07-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0046_posdaud'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGroup',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pay_group_code', models.CharField(db_column='PAY_GROUP_CODE', max_length=20, null=True)),
                ('pay_group_pic', models.BinaryField(blank=True, db_column='PAY_GROUP_PIC', null=True)),
                ('seq', models.IntegerField(blank=True, db_column='SEQ', null=True)),
                ('iscreditcard', models.BooleanField(blank=True, db_column='IsCreditCard', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('picturelocation', models.ImageField(db_column='PICTURELOCATION', null=True, upload_to='img')),
            ],
            options={
                'db_table': 'PAY_GROUP',
            },
        ),
    ]
