# Generated by Django 3.0.7 on 2023-07-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0050_deposittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multistaff',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno', models.CharField(db_column='sa_transacNo', max_length=20, null=True)),
                ('item_code', models.CharField(db_column='Item_Code', max_length=20, null=True)),
                ('emp_code', models.CharField(db_column='Emp_Code', max_length=20, null=True)),
                ('ratio', models.FloatField(db_column='Ratio', null=True)),
                ('salesamt', models.FloatField(db_column='SalesAmt', null=True)),
                ('deposit', models.FloatField(db_column='Deposit', null=True)),
                ('gt1deposit', models.FloatField(db_column='GT1Deposit', null=True)),
                ('type', models.CharField(db_column='Type', max_length=20, null=True)),
                ('isdelete', models.BooleanField(db_column='IsDelete', null=True)),
                ('role', models.CharField(db_column='Role', max_length=50, null=True)),
                ('dt_lineno', models.IntegerField(db_column='Dt_LineNo', null=True)),
                ('level_group_code', models.CharField(blank=True, db_column='Level_group_code', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('salescommpoints', models.FloatField(blank=True, db_column='SalesCommPoints', null=True)),
            ],
            options={
                'db_table': 'MultiStaff',
            },
        ),
    ]
