# Generated by Django 3.0.7 on 2023-07-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0008_auto_20230717_1317'),
        ('cl_table', '0051_multistaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmpmultistaff',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno', models.CharField(db_column='sa_transacNo', max_length=20, null=True)),
                ('item_code', models.CharField(db_column='Item_Code', max_length=20, null=True)),
                ('emp_code', models.CharField(db_column='Emp_Code', max_length=20, null=True)),
                ('ratio', models.FloatField(db_column='Ratio', null=True)),
                ('salesamt', models.FloatField(db_column='SalesAmt', null=True)),
                ('type', models.CharField(db_column='Type', max_length=20, null=True)),
                ('isdelete', models.BooleanField(db_column='IsDelete', null=True)),
                ('role', models.CharField(db_column='Role', max_length=50, null=True)),
                ('dt_lineno', models.IntegerField(db_column='dt_LineNo', null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
                ('level_group_code', models.CharField(blank=True, db_column='Level_Group_Code', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('salescommpoints', models.FloatField(blank=True, db_column='SalesCommPoints', null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
                ('itemcart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart')),
            ],
            options={
                'db_table': 'TmpMultiStaff',
            },
        ),
    ]
