# Generated by Django 3.0.7 on 2023-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0054_tmpitemhelper_pospackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptAr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(db_column='Receipt_no', max_length=20, null=True)),
                ('invoice_no', models.CharField(db_column='Invoice_No', max_length=20, null=True)),
                ('receipt_date', models.DateTimeField(db_column='Receipt_Date', null=True)),
                ('amount', models.FloatField(blank=True, db_column='aMOUNT', null=True)),
                ('emp_code', models.CharField(blank=True, db_column='Emp_Code', max_length=20, null=True)),
                ('emp_name', models.CharField(blank=True, db_column='Emp_Name', max_length=50, null=True)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=20, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=50, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Receipt_AR',
            },
        ),
    ]
