# Generated by Django 3.0.7 on 2023-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0060_skillstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStocklist',
            fields=[
                ('itemstocklist_id', models.AutoField(db_column='ItemStockList_ID', primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_column='Item_Code', max_length=20, null=True)),
                ('item_barcode', models.CharField(blank=True, db_column='Item_Barcode', max_length=20, null=True)),
                ('itemsite_code', models.CharField(blank=True, db_column='ItemSite_Code', max_length=50, null=True)),
                ('onhand_qty', models.IntegerField(blank=True, db_column='ONHAND_QTY', null=True)),
                ('itemstocklist_minqty', models.IntegerField(blank=True, db_column='ItemStockList_MinQty', null=True)),
                ('itemstocklist_maxqty', models.IntegerField(blank=True, db_column='ItemStockList_MaxQty', null=True)),
                ('onhand_cst', models.FloatField(blank=True, db_column='ONHAND_CST', null=True)),
                ('itemstocklist_onhandcost', models.FloatField(blank=True, db_column='ItemStockList_OnHandCost', null=True)),
                ('itemstocklist_unit', models.CharField(blank=True, db_column='ItemStockList_Unit', max_length=10, null=True)),
                ('itemstocklist_user', models.CharField(blank=True, db_column='ItemStockList_User', max_length=10, null=True)),
                ('itemstocklist_datetime', models.DateTimeField(blank=True, db_column='ItemStockList_DateTime', null=True)),
                ('itemstocklist_remark', models.CharField(blank=True, db_column='ItemStockList_Remark', max_length=10, null=True)),
                ('itemstocklist_posted', models.BooleanField(blank=True, db_column='ItemStockList_Posted', null=True)),
                ('itemstocklist_status', models.BooleanField(blank=True, db_column='ItemStockList_Status', null=True)),
                ('lstpo_ucst', models.FloatField(blank=True, db_column='LSTPO_UCST', null=True)),
                ('lstpo_no', models.CharField(blank=True, db_column='LSTPO_NO', max_length=20, null=True)),
                ('lstpo_date', models.DateTimeField(blank=True, db_column='LSTPO_DATE', null=True)),
                ('cost_price', models.FloatField(blank=True, db_column='COST_PRICE', null=True)),
                ('itm_seq', models.DecimalField(blank=True, db_column='ITM_SEQ', decimal_places=0, max_digits=18, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Item_StockList',
            },
        ),
    ]
