# Generated by Django 3.0.7 on 2023-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0062_itemlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, db_column='ITEM_CODE', max_length=20, null=True)),
                ('site_code', models.CharField(blank=True, db_column='SITE_CODE', max_length=20, null=True)),
                ('batch_no', models.CharField(blank=True, db_column='BATCH_NO', max_length=30, null=True)),
                ('uom', models.CharField(blank=True, db_column='UOM', max_length=20, null=True)),
                ('qty', models.FloatField(blank=True, db_column='QTY', null=True)),
                ('exp_date', models.DateTimeField(blank=True, db_column='EXP_DATE', null=True)),
                ('batch_cost', models.FloatField(blank=True, db_column='BATCH_COST', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('IsActive', models.IntegerField(blank=True, db_column='IsActive', default=1, null=True)),
            ],
            options={
                'db_table': 'ITEM_BATCH',
            },
        ),
    ]
