# Generated by Django 3.0.7 on 2023-07-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0066_treatmentprotocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUomprice',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, db_column='ITEM_CODE', max_length=20, null=True)),
                ('item_uom', models.CharField(blank=True, db_column='ITEM_UOM', max_length=20, null=True)),
                ('uom_desc', models.CharField(blank=True, db_column='UOM_DESC', max_length=50, null=True)),
                ('uom_unit', models.FloatField(blank=True, db_column='UOM_UNIT', null=True)),
                ('item_uom2', models.CharField(blank=True, db_column='ITEM_UOM2', max_length=20, null=True)),
                ('uom2_desc', models.CharField(blank=True, db_column='UOM2_DESC', max_length=50, null=True)),
                ('item_price', models.FloatField(blank=True, db_column='ITEM_PRICE', null=True)),
                ('item_cost', models.FloatField(blank=True, db_column='ITEM_COST', null=True)),
                ('min_margin', models.FloatField(blank=True, db_column='MIN_MARGIN', null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('item_uomprice_seq', models.FloatField(blank=True, db_column='Item_UOMPrice_SEQ', null=True)),
                ('delete_user', models.CharField(blank=True, db_column='Delete_User', max_length=50, null=True)),
                ('delete_date', models.DateTimeField(blank=True, db_column='Delete_Date', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'ITEM_UOMPRICE',
            },
        ),
    ]
