# Generated by Django 3.0.7 on 2023-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0067_itemuomprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDtl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=60, null=True)),
                ('cost', models.FloatField(blank=True, db_column='Cost', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=50, null=True)),
                ('package_code', models.CharField(blank=True, db_column='Package_Code', max_length=20, null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('uom', models.CharField(blank=True, db_column='UOM', max_length=50, null=True)),
                ('package_barcode', models.CharField(blank=True, db_column='Package_Barcode', max_length=20, null=True)),
                ('disc_percent', models.IntegerField(blank=True, db_column='Disc_Percent', null=True)),
                ('unit_price', models.FloatField(blank=True, db_column='Unit_Price', null=True)),
                ('ttl_uprice', models.FloatField(blank=True, db_column='Ttl_UPrice', null=True)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=50)),
                ('line_no', models.IntegerField(blank=True, db_column='Line_no', null=True)),
                ('service_expire_active', models.BooleanField(db_column='Service_Expire_Active', null=True)),
                ('service_expire_month', models.FloatField(blank=True, db_column='Service_Expire_Month', null=True)),
                ('treatment_limit_active', models.BooleanField(db_column='Treatment_Limit_Active', null=True)),
                ('treatment_limit_count', models.FloatField(blank=True, db_column='Treatment_Limit_Count', null=True)),
                ('limitservice_flexionly', models.BooleanField(db_column='LimitService_FlexiOnly', null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Package_Dtl',
            },
        ),
    ]
