# Generated by Django 3.0.7 on 2023-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0068_packagedtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHdr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=60, null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=50, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date_Created', null=True)),
                ('time_created', models.DateTimeField(blank=True, db_column='Time_Created', null=True)),
                ('user_name', models.CharField(blank=True, db_column='User_Name', max_length=20, null=True)),
                ('package_barcode', models.CharField(blank=True, db_column='Package_Barcode', max_length=20, null=True)),
                ('unit_price', models.FloatField(blank=True, db_column='Unit_Price', null=True)),
                ('from_date', models.DateTimeField(blank=True, db_column='From_date', null=True)),
                ('to_date', models.DateTimeField(blank=True, db_column='To_date', null=True)),
                ('from_time', models.DateTimeField(blank=True, db_column='From_Time', null=True)),
                ('to_time', models.DateTimeField(blank=True, db_column='To_Time', null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('manual_disc', models.BooleanField(blank=True, db_column='Manual_disc', null=True)),
                ('istdt', models.BooleanField(blank=True, db_column='IsTDT', null=True)),
                ('apptlimit', models.IntegerField(blank=True, db_column='ApptLimit', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Package_Hdr',
            },
        ),
    ]
