# Generated by Django 3.0.7 on 2023-07-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0008_auto_20230717_1317'),
        ('cl_table', '0069_packagehdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidOpenCondition',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('p_itemtype', models.CharField(db_column='P_ItemType', max_length=20, null=True)),
                ('item_code', models.CharField(max_length=20, null=True)),
                ('conditiontype1', models.CharField(db_column='ConditionType1', max_length=80, null=True)),
                ('conditiontype2', models.CharField(db_column='ConditionType2', max_length=80, null=True)),
                ('prepaid_value', models.FloatField(blank=True, db_column='Prepaid_Value', null=True)),
                ('prepaid_sell_amt', models.FloatField(blank=True, db_column='Prepaid_Sell_Amt', null=True)),
                ('prepaid_valid_period', models.CharField(db_column='Prepaid_Valid_Period', max_length=20, null=True)),
                ('rate', models.CharField(db_column='Rate', max_length=10, null=True)),
                ('membercardnoaccess', models.BooleanField(db_column='MemberCardNoAccess', null=True)),
                ('uid', models.CharField(db_column='UID', max_length=36, null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
                ('pp_uid_ref', models.CharField(blank=True, db_column='PP_UID_Ref', max_length=50, null=True)),
                ('creditvalueshared', models.BooleanField(db_column='CreditValueShared')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('itemdept_id', models.IntegerField(blank=True, db_column='itemdept_id', null=True)),
                ('itembrand_id', models.IntegerField(blank=True, db_column='itembrand_id', null=True)),
                ('itemcart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart')),
            ],
            options={
                'db_table': 'Prepaid_Open_Condition',
            },
        ),
    ]
