# Generated by Django 3.0.7 on 2023-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0070_prepaidopencondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleHour',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('itm_code', models.CharField(blank=True, db_column='itm_Code', max_length=50, null=True)),
                ('itm_desc', models.CharField(blank=True, db_column='itm_Desc', max_length=100, null=True)),
                ('fromtime', models.DateTimeField(blank=True, db_column='FromTime', null=True)),
                ('totime', models.DateTimeField(blank=True, db_column='ToTime', null=True)),
                ('offday', models.BooleanField(db_column='OFFDAY', null=True)),
                ('itm_isactive', models.BooleanField(blank=True, db_column='ITM_ISACTIVE', default=True, null=True)),
                ('itm_type', models.CharField(blank=True, max_length=50, null=True)),
                ('itm_color', models.CharField(blank=True, db_column='itm_Color', max_length=50, null=True)),
                ('timeframe', models.CharField(db_column='TimeFrame', max_length=20, null=True)),
                ('shortDesc', models.CharField(db_column='shortDesc', max_length=2, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Schedule_Hour',
            },
        ),
    ]
