# Generated by Django 3.0.7 on 2023-07-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0071_schedulehour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMonth',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emp_code', models.CharField(blank=True, db_column='Emp_Code', max_length=50, null=True)),
                ('itm_date', models.DateTimeField(blank=True, db_column='itm_Date', null=True)),
                ('itm_type', models.CharField(blank=True, db_column='itm_Type', max_length=50, null=True)),
                ('ledit', models.BooleanField(db_column='lEdit', null=True)),
                ('ledittype', models.CharField(blank=True, db_column='lEditType', max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, db_column='User_Name', max_length=50, null=True)),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('totalappointments', models.IntegerField(blank=True, null=True)),
                ('time07', models.BooleanField(blank=True, default=False, null=True)),
                ('time0730', models.BooleanField(blank=True, default=False, null=True)),
                ('time08', models.BooleanField(blank=True, default=False, null=True)),
                ('time0830', models.BooleanField(blank=True, default=False, null=True)),
                ('time09', models.BooleanField(blank=True, default=False, null=True)),
                ('time0930', models.BooleanField(blank=True, default=False, null=True)),
                ('time10', models.BooleanField(blank=True, default=False, null=True)),
                ('time1030', models.BooleanField(blank=True, default=False, null=True)),
                ('time11', models.BooleanField(blank=True, default=False, null=True)),
                ('time1130', models.BooleanField(blank=True, default=False, null=True)),
                ('time12', models.BooleanField(blank=True, default=False, null=True)),
                ('time1230', models.BooleanField(blank=True, default=False, null=True)),
                ('time13', models.BooleanField(blank=True, default=False, null=True)),
                ('time1330', models.BooleanField(blank=True, default=False, null=True)),
                ('time14', models.BooleanField(blank=True, default=False, null=True)),
                ('time1430', models.BooleanField(blank=True, default=False, null=True)),
                ('time15', models.BooleanField(blank=True, default=False, null=True)),
                ('time1530', models.BooleanField(blank=True, default=False, null=True)),
                ('time16', models.BooleanField(blank=True, default=False, null=True)),
                ('time1630', models.BooleanField(blank=True, default=False, null=True)),
                ('time17', models.BooleanField(blank=True, default=False, null=True)),
                ('time1730', models.BooleanField(blank=True, default=False, null=True)),
                ('time18', models.BooleanField(blank=True, default=False, null=True)),
                ('time1830', models.BooleanField(blank=True, default=False, null=True)),
                ('time19', models.BooleanField(blank=True, default=False, null=True)),
                ('time1930', models.BooleanField(blank=True, default=False, null=True)),
                ('time20', models.BooleanField(blank=True, default=False, null=True)),
                ('time2030', models.BooleanField(blank=True, default=False, null=True)),
                ('time21', models.BooleanField(blank=True, default=False, null=True)),
                ('time2130', models.BooleanField(blank=True, default=False, null=True)),
                ('time22', models.BooleanField(blank=True, default=False, null=True)),
                ('time2230', models.BooleanField(blank=True, default=False, null=True)),
                ('time23', models.BooleanField(blank=True, default=False, null=True)),
                ('time2330', models.BooleanField(blank=True, default=False, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Emp_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
                ('User_Nameid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
                ('itm_Typeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.ScheduleHour')),
            ],
            options={
                'db_table': 'Schedule_Month',
            },
        ),
    ]
