# Generated by Django 3.0.7 on 2023-07-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0072_schedulemonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workschedule',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('monday', models.CharField(blank=True, db_column='Monday', max_length=20, null=True)),
                ('tuesday', models.CharField(blank=True, db_column='Tuesday', max_length=20, null=True)),
                ('wednesday', models.CharField(blank=True, db_column='Wednesday', max_length=20, null=True)),
                ('thursday', models.CharField(blank=True, db_column='Thursday', max_length=20, null=True)),
                ('friday', models.CharField(blank=True, db_column='Friday', max_length=20, null=True)),
                ('saturday', models.CharField(blank=True, db_column='Saturday', max_length=20, null=True)),
                ('sunday', models.CharField(blank=True, db_column='Sunday', max_length=20, null=True)),
                ('emp_code', models.CharField(blank=True, db_column='Emp_Code', max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_alternative', models.BooleanField(db_column='is_alter', default=False)),
            ],
            options={
                'db_table': 'WorkSchedule',
            },
        ),
    ]
