# Generated by Django 3.0.7 on 2023-07-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0073_workschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttnType',
            fields=[
                ('attn_id', models.AutoField(db_column='Attn_id', primary_key=True, serialize=False)),
                ('attn_code', models.CharField(blank=True, db_column='Attn_code', max_length=10, null=True)),
                ('attn_desc', models.CharField(blank=True, db_column='Attn_desc', max_length=40, null=True)),
                ('attn_isactive', models.BooleanField(db_column='Attn_isactive', default=True)),
                ('attn_mov_in', models.CharField(blank=True, db_column='Attn_Mov_In', max_length=50, null=True)),
                ('attn_seq', models.FloatField(blank=True, db_column='Attn_Seq', null=True)),
                ('attn_spec_in', models.BooleanField(db_column='Attn_Spec_In', null=True)),
                ('attn_spec_out', models.BooleanField(db_column='Attn_Spec_Out', null=True)),
                ('show_when_norecord', models.BooleanField(db_column='Show_When_NoRecord', null=True)),
                ('show_when_workin_on', models.BooleanField(db_column='Show_When_WorkIn_On', null=True)),
                ('show_when_workout_on', models.BooleanField(db_column='Show_When_WorkOut_On', null=True)),
                ('show_when_breakin_on', models.BooleanField(db_column='Show_When_BreakIn_On', null=True)),
                ('show_when_breakout_on', models.BooleanField(db_column='Show_When_BreakOut_On', null=True)),
                ('show_when_lunchin_on', models.BooleanField(db_column='Show_When_LunchIn_On', null=True)),
                ('show_when_lunchout_on', models.BooleanField(db_column='Show_When_LunchOut_On', null=True)),
                ('show_when_dinnerin_on', models.BooleanField(db_column='Show_When_DinnerIn_On', null=True)),
                ('show_when_dinnerout_on', models.BooleanField(db_column='Show_When_DinnerOut_On', null=True)),
                ('show_when_specialin_on', models.BooleanField(db_column='Show_When_SpecialIn_On', null=True)),
                ('show_when_specialout_on', models.BooleanField(db_column='Show_When_SpecialOut_On', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Attn_Type',
            },
        ),
    ]
