# Generated by Django 3.0.7 on 2023-07-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0074_attntype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSitelist',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emp_code', models.CharField(db_column='Emp_Code', max_length=20, null=True)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=20, null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hide_in_appt', models.BooleanField(db_column='hide_in_appt', default=False)),
                ('emp_seq_webappt', models.IntegerField(blank=True, db_column='Emp_Seq_WebAppt', null=True)),
                ('Emp_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'Emp_SiteList',
                'unique_together': {('emp_code', 'site_code')},
            },
        ),
    ]
