# Generated by Django 3.0.7 on 2023-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0077_appointmentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmentdetails',
            fields=[
                ('apptid', models.BigAutoField(db_column='ApptId', primary_key=True, serialize=False)),
                ('appt_code', models.CharField(db_column='Appt_code', max_length=50, null=True)),
                ('linenumber', models.IntegerField(blank=True, db_column='lineNumber', null=True)),
                ('itemcode', models.CharField(blank=True, db_column='itemCode', max_length=20, null=True)),
                ('itemname', models.CharField(blank=True, db_column='itemName', max_length=40, null=True)),
                ('unitprice', models.FloatField(blank=True, db_column='unitPrice', null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='isActive', default=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'AppointmentDetails',
            },
        ),
    ]
