# Generated by Django 3.0.7 on 2023-07-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0080_templatesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNo',
            fields=[
                ('control_no', models.CharField(blank=True, max_length=50, null=True)),
                ('control_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('control_description', models.CharField(blank=True, max_length=50, null=True)),
                ('control_id', models.AutoField(primary_key=True, serialize=False)),
                ('controldate', models.DateField(blank=True, db_column='CONTROLDATE', max_length=20, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('mac_code', models.CharField(blank=True, db_column='Mac_Code', max_length=4, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('include_sitecode', models.BooleanField(blank=True, default=False, null=True)),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'Control_No',
            },
        ),
    ]
