# Generated by Django 3.0.7 on 2023-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0081_controlno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systemlog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('log_type', models.CharField(blank=True, db_column='Log_Type', max_length=50, null=True)),
                ('log_datetime', models.DateTimeField(blank=True, db_column='Log_DateTime', null=True)),
                ('log_user', models.CharField(blank=True, db_column='Log_User', max_length=50, null=True)),
                ('log_process', models.CharField(blank=True, db_column='Log_Process', max_length=50, null=True)),
                ('log_message', models.CharField(blank=True, db_column='Log_Message', max_length=3000, null=True)),
                ('log_site_code', models.CharField(blank=True, db_column='Log_Site_Code', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'SystemLog',
            },
        ),
        migrations.CreateModel(
            name='Systemloginlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(blank=True, db_column='Log_Type', max_length=50, null=True)),
                ('log_datetime', models.DateTimeField(blank=True, db_column='Log_DateTime', null=True)),
                ('log_user', models.CharField(blank=True, db_column='Log_User', max_length=50, null=True)),
                ('log_process', models.CharField(blank=True, db_column='Log_Process', max_length=50, null=True)),
                ('log_message', models.CharField(blank=True, db_column='Log_Message', max_length=3000, null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
                ('log_terminalcode', models.CharField(blank=True, db_column='Log_TerminalCode', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'SystemLoginLog',
            },
        ),
    ]
