# Generated by Django 3.0.7 on 2023-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0083_gstsetting_systemsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockReason',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('b_no', models.CharField(blank=True, db_column='B_No', max_length=50, null=True)),
                ('b_reason', models.CharField(blank=True, db_column='B_Reason', max_length=50, null=True)),
                ('active', models.BooleanField(blank=True, db_column='Active', default=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Block_Reason',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_desc', models.CharField(blank=True, db_column='ITM_DESC', max_length=40, null=True)),
                ('itm_code', models.CharField(blank=True, db_column='ITM_CODE', max_length=40, null=True)),
                ('itm_isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Language',
            },
        ),
    ]
