# Generated by Django 3.0.7 on 2023-07-17 14:02

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0085_exchangedtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFormControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, db_column='fieldName', max_length=50, null=True)),
                ('display_field_name', models.CharField(blank=True, db_column='displayFieldName', max_length=50, null=True)),
                ('visible_in_registration', models.BooleanField(db_column='visibleInRegistration')),
                ('visible_in_listing', models.BooleanField(db_column='visibleInListing')),
                ('visible_in_profile', models.BooleanField(db_column='visibleInProfile')),
                ('editable', models.BooleanField()),
                ('mandatory', models.BooleanField()),
                ('order', models.IntegerField()),
                ('col_width', models.IntegerField(default=6)),
                ('isActive', models.BooleanField(db_column='isActive')),
                ('isStacked', models.BooleanField(db_column='isStacked', default=False)),
                ('showLabel', models.BooleanField(default=True)),
                ('layout', jsonfield.fields.JSONField(default={'lg': {'h': 0, 'w': 0, 'x': 0, 'y': 0}, 'md': {'h': 0, 'w': 0, 'x': 0, 'y': 0}, 'sm': {'h': 0, 'w': 0, 'x': 0, 'y': 0}})),
                ('Site_Codeid', models.ForeignKey(db_column='Site_Codeid_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_form_control', to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'customerFormControl',
            },
        ),
    ]
