# Generated by Django 3.0.7 on 2023-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0087_mrrewarditemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPolicy',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('reward_code', models.CharField(db_column='Reward_Code', max_length=20)),
                ('cust_type', models.CharField(db_column='Cust_Type', max_length=20)),
                ('cur_value', models.FloatField(db_column='Cur_Value')),
                ('point_value', models.FloatField(db_column='Point_Value')),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('reward_item_type', models.CharField(blank=True, db_column='Reward_Item_Type', max_length=20, null=True)),
                ('brand_ids', models.ManyToManyField(blank=True, to='cl_table.ItemBrand')),
                ('dept_ids', models.ManyToManyField(blank=True, to='cl_table.ItemDept')),
                ('item_divids', models.ManyToManyField(blank=True, related_name='multi_item_divid', to='cl_table.ItemDiv')),
            ],
            options={
                'db_table': 'Reward_Policy',
            },
        ),
    ]
