# Generated by Django 3.0.7 on 2023-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0088_rewardpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemPolicy',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('redeem_code', models.CharField(db_column='Redeem_Code', max_length=20)),
                ('cust_type', models.CharField(db_column='Cust_Type', max_length=20)),
                ('cur_value', models.FloatField(db_column='Cur_Value')),
                ('point_value', models.FloatField(db_column='Point_Value')),
                ('isactive', models.BooleanField(db_column='IsActive')),
                ('brand_ids', models.ManyToManyField(blank=True, to='cl_table.ItemBrand')),
                ('dept_ids', models.ManyToManyField(blank=True, to='cl_table.ItemDept')),
                ('item_divids', models.ManyToManyField(blank=True, to='cl_table.ItemDiv')),
            ],
            options={
                'db_table': 'Redeem_Policy',
            },
        ),
    ]
