# Generated by Django 3.0.7 on 2023-07-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0089_redeempolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('sys_code', models.AutoField(db_column='Sys_Code', primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateTimeField(blank=True, db_column='Diagnosis_Date', null=True)),
                ('next_appt', models.DateTimeField(blank=True, db_column='Next_Appt', null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=255, null=True)),
                ('homecare', models.CharField(blank=True, db_column='HomeCare', max_length=255, null=True)),
                ('date_pic_take', models.DateTimeField(blank=True, db_column='Date_Pic_Take', null=True)),
                ('treatment_code', models.CharField(blank=True, db_column='Treatment_Code', max_length=50, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=100, null=True)),
                ('cust_code', models.CharField(db_column='Cust_Code', max_length=50)),
                ('diagnosis_code', models.CharField(blank=True, db_column='Diagnosis_Code', max_length=50, null=True)),
                ('left_desc1', models.CharField(blank=True, db_column='Left_Desc1', max_length=100, null=True)),
                ('left_desc2', models.CharField(blank=True, db_column='Left_Desc2', max_length=100, null=True)),
                ('right_desc1', models.CharField(blank=True, db_column='Right_Desc1', max_length=100, null=True)),
                ('right_desc2', models.CharField(blank=True, db_column='Right_Desc2', max_length=100, null=True)),
                ('treatment_name', models.CharField(blank=True, db_column='Treatment_Name', max_length=50, null=True)),
                ('remark1', models.CharField(blank=True, db_column='Remark1', max_length=200, null=True)),
                ('remark2', models.CharField(blank=True, db_column='Remark2', max_length=200, null=True)),
                ('remark3', models.CharField(blank=True, db_column='Remark3', max_length=200, null=True)),
                ('remark4', models.CharField(blank=True, db_column='Remark4', max_length=200, null=True)),
                ('remark5', models.CharField(blank=True, db_column='Remark5', max_length=200, null=True)),
                ('remark6', models.CharField(blank=True, db_column='Remark6', max_length=200, null=True)),
                ('pic_path', models.ImageField(blank=True, db_column='PIC_path', max_length=255, null=True, upload_to='img')),
                ('pic_path2', models.ImageField(blank=True, db_column='PIC_Path2', max_length=255, null=True, upload_to='img')),
                ('pic_path3', models.ImageField(blank=True, db_column='PIC_Path3', max_length=255, null=True, upload_to='img')),
                ('pic_path4', models.ImageField(blank=True, db_column='PIC_Path4', max_length=255, null=True, upload_to='img')),
                ('pic_path5', models.ImageField(blank=True, db_column='PIC_Path5', max_length=255, null=True, upload_to='img')),
                ('pic_path6', models.ImageField(blank=True, db_column='PIC_Path6', max_length=255, null=True, upload_to='img')),
                ('pic_data', models.FileField(blank=True, null=True, upload_to='')),
                ('pic_data1', models.TextField(blank=True, null=True)),
                ('pic1', models.BinaryField(blank=True, db_column='PIC1', null=True)),
                ('pic2', models.BinaryField(blank=True, db_column='PIC2', null=True)),
                ('pic3', models.BinaryField(blank=True, db_column='PIC3', null=True)),
                ('pic4', models.BinaryField(blank=True, db_column='PIC4', null=True)),
                ('pic5', models.BinaryField(blank=True, db_column='PIC5', null=True)),
                ('pic6', models.BinaryField(blank=True, db_column='PIC6', null=True)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=50)),
                ('cust_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
            ],
            options={
                'db_table': 'Diagnosis',
                'unique_together': {('sys_code', 'cust_no', 'site_code')},
            },
        ),
    ]
