# Generated by Django 3.0.7 on 2023-07-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0091_diagnosiscompare'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPoint',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('transacno', models.CharField(db_column='TransacNO', max_length=20)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, db_column='Time', null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=100, null=True)),
                ('cust_code', models.CharField(db_column='Cust_Code', max_length=100)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=20, null=True)),
                ('refno', models.CharField(db_column='RefNo', max_length=20)),
                ('ref_source', models.CharField(db_column='Ref_Source', max_length=50)),
                ('isvoid', models.BooleanField(db_column='Isvoid', default=True)),
                ('sa_status', models.CharField(db_column='Sa_Status', max_length=10)),
                ('void_referenceno', models.CharField(blank=True, db_column='void_ReferenceNo', max_length=20, null=True)),
                ('total_point', models.FloatField(db_column='Total_Point')),
                ('now_point', models.FloatField(blank=True, db_column='Now_Point', null=True)),
                ('seq', models.IntegerField(blank=True, db_column='Seq', null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=100, null=True)),
                ('bal_point', models.FloatField(db_column='Bal_Point', default=0)),
                ('expired', models.BooleanField(db_column='Expired', default=False)),
                ('expired_date', models.DateTimeField(blank=True, db_column='Expired_Date', null=True)),
                ('mac_code', models.CharField(db_column='Mac_Code', default='', max_length=100)),
                ('logno', models.CharField(db_column='LogNo', default='', max_length=100)),
                ('approval_user', models.CharField(db_column='Approval_User', default='', max_length=100)),
                ('cardno', models.CharField(db_column='CardNo', default='', max_length=100)),
                ('bdate', models.DateTimeField(blank=True, db_column='BDate', null=True)),
                ('pdate', models.DateTimeField(blank=True, db_column='PDate', null=True)),
                ('expired_point', models.FloatField(blank=True, default=0)),
                ('postransactionno', models.CharField(db_column='posTransactionNo', default='', max_length=50)),
                ('postotalamt', models.FloatField(blank=True, db_column='posTotalAmt', null=True)),
                ('locid', models.CharField(db_column='LocID', default='', max_length=50)),
                ('mgm_refno', models.CharField(blank=True, db_column='MGM_RefNo', max_length=20, null=True)),
                ('tdate', models.CharField(blank=True, db_column='TDate', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Customer_Point',
                'unique_together': {('transacno', 'cust_code', 'sa_status', 'total_point', 'postransactionno', 'locid')},
            },
        ),
    ]
