# Generated by Django 3.0.7 on 2023-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0093_customerpointdtl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multilanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english', models.CharField(blank=True, max_length=250, null=True)),
                ('zh_sg', models.CharField(blank=True, db_column='zh-sg', max_length=250, null=True)),
            ],
            options={
                'db_table': 'MultiLanguage',
            },
        ),
    ]
