# Generated by Django 3.0.7 on 2023-07-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0094_multilanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wordCode', models.IntegerField()),
                ('word', models.CharField(max_length=250)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cl_table.Language')),
            ],
            options={
                'db_table': 'MultiLanguageWord',
                'unique_together': {('wordCode', 'language')},
            },
        ),
    ]
