# Generated by Django 3.0.7 on 2023-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0095_multilanguageword'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailysalesdataDetail',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sitecode', models.CharField(db_column='SiteCode', max_length=20)),
                ('sales_date', models.DateTimeField(db_column='Sales_Date')),
                ('business_date', models.DateTimeField(db_column='Business_Date')),
                ('sa_transacno', models.CharField(blank=True, db_column='SA_TransacNo', max_length=20, null=True)),
                ('sa_transacno_ref', models.CharField(blank=True, db_column='SA_TransacNo_Ref', max_length=20, null=True)),
                ('version', models.CharField(blank=True, db_column='Version', max_length=20, null=True)),
                ('sales_gt1_withgst', models.FloatField(blank=True, db_column='Sales_GT1_WithGST', null=True)),
                ('sales_gt1_gst', models.FloatField(blank=True, db_column='Sales_GT1_GST', null=True)),
                ('sales_gt1_beforegst', models.FloatField(blank=True, db_column='Sales_GT1_BeforeGST', null=True)),
                ('servicesales_gt1', models.FloatField(blank=True, db_column='ServiceSales_GT1', null=True)),
                ('productsales_gt1', models.FloatField(blank=True, db_column='ProductSales_GT1', null=True)),
                ('prepaidsales_gt1', models.FloatField(blank=True, db_column='PrepaidSales_GT1', null=True)),
                ('sales_gt2_withgst', models.FloatField(blank=True, db_column='Sales_GT2_WithGST', null=True)),
                ('sales_gt2_gst', models.FloatField(blank=True, db_column='Sales_GT2_GST', null=True)),
                ('sales_gt2_beforegst', models.FloatField(blank=True, db_column='Sales_GT2_BeforeGST', null=True)),
                ('servicesales_gt2', models.FloatField(blank=True, db_column='ServiceSales_GT2', null=True)),
                ('productsales_gt2', models.FloatField(blank=True, db_column='ProductSales_GT2', null=True)),
                ('prepaidsales_gt2', models.FloatField(blank=True, db_column='PrepaidSales_GT2', null=True)),
                ('treatmentdoneqty', models.FloatField(blank=True, db_column='TreatmentDoneQty', null=True)),
                ('treatmentdoneamount', models.FloatField(blank=True, db_column='TreatmentDoneAmount', null=True)),
                ('lastupdate', models.DateTimeField(db_column='LastUpDate')),
                ('processlog_ref', models.CharField(blank=True, db_column='ProcessLog_Ref', max_length=20, null=True)),
                ('vouchersales_gt1', models.FloatField(blank=True, db_column='VoucherSales_GT1', null=True)),
                ('vouchersales_gt2', models.FloatField(blank=True, db_column='VoucherSales_GT2', null=True)),
            ],
            options={
                'db_table': 'DailySalesData_Detail',
            },
        ),
    ]
