# Generated by Django 3.0.7 on 2023-07-17 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0099_smsreceivelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempcustsign',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=50, null=True)),
                ('transaction_no', models.CharField(blank=True, db_column='Transaction_No', max_length=50, null=True)),
                ('cust_sig', models.ImageField(blank=True, db_column='Cust_Sig', null=True, upload_to='img')),
                ('site_code', models.CharField(blank=True, db_column='SITE_CODE', max_length=4, null=True)),
                ('mac_code', models.CharField(blank=True, db_column='MAC_CODE', max_length=3, null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=36, null=True)),
                ('cart_id', models.CharField(blank=True, db_column='cart_id', max_length=250, null=True)),
            ],
            options={
                'db_table': 'TempCustSign',
            },
        ),
        migrations.CreateModel(
            name='PackageAuditingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_parentcode', models.CharField(blank=True, db_column='Treatment_ParentCode', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('package_type', models.CharField(blank=True, choices=[('Reversal', 'Reversal'), ('Void', 'Void'), ('Exchange', 'Exchange'), ('Redeem', 'Redeem')], db_column='package_type', max_length=20, null=True)),
                ('pa_qty', models.IntegerField(blank=True, db_column='pa_qty', null=True)),
                ('user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'PackageAuditingLog',
            },
        ),
    ]
