# Generated by Django 3.0.7 on 2023-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0101_customerdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustLogAudit',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=500, null=True)),
                ('username', models.CharField(blank=True, db_column='username', max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'CustLogAudit',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=500, null=True)),
                ('designation', models.CharField(blank=True, db_column='designation', max_length=500, null=True)),
                ('mobile_phone', models.CharField(blank=True, db_column='Mobile_phone', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=255, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
            ],
            options={
                'db_table': 'ContactPerson',
            },
        ),
    ]
