# Generated by Django 3.0.7 on 2023-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0102_contactperson_custlogaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFlexiservice',
            fields=[
                ('itm_id', models.AutoField(db_column='itm_ID', primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, db_column='Item_Code', max_length=500, null=True)),
                ('item_srvcode', models.CharField(blank=True, db_column='Item_SrvCode', max_length=500, null=True)),
                ('item_srvdesc', models.CharField(blank=True, db_column='Item_SrvDesc', max_length=500, null=True)),
                ('itm_isactive', models.BooleanField(db_column='Itm_IsActive', default=True)),
                ('item_srvid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock')),
            ],
            options={
                'db_table': 'Item_FlexiService',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='username', max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('pp_no', models.CharField(db_column='PP_NO', max_length=500, null=True)),
                ('line_no', models.BigIntegerField(db_column='Line_No', null=True)),
                ('user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'AuditLog',
            },
        ),
    ]
