# Generated by Django 3.0.7 on 2023-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0103_auditlog_itemflexiservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='termsandcondition',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('template_name', models.CharField(blank=True, db_column='template_name', max_length=500, null=True)),
                ('template_text', models.TextField(blank=True, db_column='template_text', null=True)),
                ('isactive', models.BooleanField(db_column='isactive', default=True)),
            ],
            options={
                'db_table': 'termsandcondition',
            },
        ),
        migrations.CreateModel(
            name='Dayendconfirmlog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='username', max_length=500, null=True)),
                ('dayend_date', models.DateField(blank=True, db_column='dayend_date', null=True)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('dayend_pdf', models.ImageField(max_length=300, null=True, upload_to='img')),
                ('isdayend', models.BooleanField(blank=True, db_column='isdayend', null=True)),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
                ('user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'Dayendconfirmlog',
            },
        ),
    ]
