# Generated by Django 3.0.7 on 2023-07-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0105_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioWork',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('work', models.CharField(blank=True, db_column='work', max_length=500, null=True)),
                ('dateplus', models.IntegerField(blank=True, db_column='dateplus', null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
            ],
            options={
                'db_table': 'StudioWork',
            },
        ),
    ]
