# Generated by Django 3.0.7 on 2023-07-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_tmpitemhelpersession'),
        ('cl_table', '0107_mgmpolicycloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitelistip',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, db_column='ip', max_length=500, null=True)),
                ('isactive', models.BooleanField(db_column='isactive', default=True)),
                ('siteid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'sitelistip',
                'unique_together': {('siteid', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='CustomerReferral',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=20, null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('rewards_given', models.IntegerField(db_column='rewards_given', default=0)),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custid', to='cl_table.Customer')),
                ('referral_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referralid', to='cl_table.Customer')),
            ],
            options={
                'db_table': 'CustomerReferral',
                'unique_together': {('referral_id', 'cust_id', 'Site_Codeid')},
            },
        ),
    ]
