# Generated by Django 3.0.7 on 2023-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0110_displaycatalog_displayitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletRequestLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(blank=True, db_column='Log_Date', null=True)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=200, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=200, null=True)),
                ('from_site', models.CharField(blank=True, db_column='From_Site', max_length=200, null=True)),
                ('requesting_site', models.CharField(blank=True, db_column='Requesting_Site', max_length=200, null=True)),
                ('last_transaction', models.CharField(blank=True, db_column='Last_Transaction', max_length=200, null=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, db_column='Last_Transaction_Date', null=True)),
                ('request_by', models.CharField(blank=True, db_column='Request_By', max_length=200, null=True)),
                ('req_date', models.DateTimeField(blank=True, db_column='Req_Date', null=True)),
                ('req_status', models.CharField(blank=True, db_column='Req_Status', max_length=20, null=True)),
                ('req_staff_code', models.CharField(blank=True, db_column='Req_Staff_Code', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Outlet_Request_Log',
            },
        ),
    ]
