# Generated by Django 3.0.7 on 2023-09-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0113_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidaccount',
            name='preacc_useid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prepaidaccountcondition',
            name='topup_remain',
            field=models.FloatField(blank=True, db_column='Topup_Remain', null=True),
        ),
    ]
