# Generated by Django 3.0.7 on 2023-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0132_auto_20230919_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlog',
            name='add_duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointmentlog',
            name='appt_fr_time',
            field=models.TimeField(blank=True, db_column='Appt_Fr_time', null=True),
        ),
        migrations.AlterField(
            model_name='appointmentlog',
            name='appt_to_time',
            field=models.TimeField(blank=True, db_column='Appt_To_time', null=True),
        ),
    ]
