# Generated by Django 3.0.7 on 2023-11-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0137_customer_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmspw',
            name='flgPoint',
            field=models.BooleanField(db_column='flgPoint', default=False),
        ),
        migrations.AddField(
            model_name='invoicetemplate',
            name='order_seq',
            field=models.IntegerField(blank=True, db_column='Order_Seq', null=True),
        ),
        migrations.AddField(
            model_name='itembatchsno',
            name='itemcart',
            field=models.IntegerField(blank=True, db_column='itemcart', null=True),
        ),
    ]
