# Generated by Django 3.0.7 on 2023-11-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0138_auto_20231115_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidaccount',
            name='sa_date',
            field=models.DateTimeField(blank=True, db_column='SA_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccount',
            name='start_date',
            field=models.DateTimeField(blank=True, db_column='START_DATE', null=True),
        ),
    ]
