# Generated by Django 3.0.7 on 2023-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=20, null=True)),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
                ('is_delete', models.BooleanField(db_column='Is_Delete', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Site_Group',
            },
        ),
    ]
