# Generated by Django 3.0.7 on 2023-07-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0002_securities'),
        ('cl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSitelist',
            fields=[
                ('itemsite_id', models.BigAutoField(db_column='ItemSite_ID', primary_key=True, serialize=False)),
                ('itemsite_code', models.CharField(db_column='ItemSite_Code', max_length=20, null=True)),
                ('itemsite_desc', models.CharField(blank=True, db_column='ItemSite_Desc', max_length=60, null=True)),
                ('itemsite_type', models.CharField(blank=True, db_column='ItemSite_Type', max_length=10, null=True)),
                ('item_purchasedept', models.CharField(blank=True, db_column='Item_PurchaseDept', max_length=20, null=True)),
                ('itemsite_address', models.CharField(blank=True, db_column='ItemSite_Address', max_length=255, null=True)),
                ('itemsite_postcode', models.CharField(blank=True, db_column='ItemSite_Postcode', max_length=20, null=True)),
                ('itemsite_city', models.CharField(blank=True, db_column='ItemSite_City', max_length=50, null=True)),
                ('itemsite_state', models.CharField(blank=True, db_column='ItemSite_State', max_length=50, null=True)),
                ('itemsite_country', models.CharField(blank=True, db_column='ItemSite_Country', max_length=50, null=True)),
                ('itemsite_phone1', models.CharField(db_column='ItemSite_Phone1', max_length=50, null=True)),
                ('itemsite_phone2', models.CharField(blank=True, db_column='ItemSite_Phone2', max_length=50, null=True)),
                ('itemsite_fax', models.CharField(blank=True, db_column='ItemSite_Fax', max_length=50, null=True)),
                ('itemsite_email', models.EmailField(blank=True, db_column='ItemSite_Email', max_length=50, null=True)),
                ('itemsite_user', models.CharField(blank=True, db_column='ItemSite_User', max_length=50, null=True)),
                ('itemsite_date', models.DateField(blank=True, db_column='ItemSite_Date', null=True)),
                ('itemsite_time', models.DateTimeField(blank=True, db_column='ItemSite_Time', null=True)),
                ('itemsite_isactive', models.BooleanField(db_column='ItemSite_Isactive', default=True)),
                ('itemsite_refcode', models.CharField(blank=True, db_column='ITEMSITE_REFCODE', max_length=20, null=True)),
                ('site_group', models.CharField(blank=True, db_column='Site_Group', max_length=50, null=True)),
                ('site_is_gst', models.BooleanField(db_column='SITE_IS_GST', default=False, null=True)),
                ('account_code', models.CharField(blank=True, db_column='Account_Code', max_length=20, null=True)),
                ('clientindex', models.BigIntegerField(blank=True, db_column='ClientIndex', null=True)),
                ('heartbeat', models.DateTimeField(blank=True, db_column='HeartBeat', null=True)),
                ('systemlog_mdpl_update', models.BooleanField(db_column='SystemLog_MDPL_Update', default=False, null=True)),
                ('ratings', models.CharField(blank=True, db_column='Ratings', max_length=40, null=True)),
                ('pic_path', models.TextField(blank=True, db_column='pic_Path', null=True)),
                ('qrcode', models.CharField(blank=True, db_column='QRCode', max_length=40, null=True)),
                ('sitedbconnectionurl', models.CharField(blank=True, db_column='siteDbConnectionUrl', max_length=100, null=True)),
                ('geolink', models.CharField(blank=True, max_length=100, null=True)),
                ('weekdays_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('weekend_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('holliday_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_on', models.CharField(blank=True, db_column='Closed_on', max_length=100, null=True)),
                ('picpath', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, db_column='Owner', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('skills_list', models.CharField(max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('service_sel', models.BooleanField(db_column='Service_Selection', default=False)),
                ('service_text', models.BooleanField(db_column='Service_Text', default=False)),
                ('is_nric', models.BooleanField(db_column='Nric', default=False)),
                ('is_automember', models.BooleanField(db_column='IsAutoMember', default=False)),
                ('startday_hour', models.CharField(blank=True, db_column='StartDay_Hour', max_length=100, null=True)),
                ('endday_hour', models.CharField(blank=True, db_column='EndDay_Hour', max_length=100, null=True)),
                ('cell_duration', models.CharField(blank=True, db_column='Cell_Duration', max_length=100, null=True)),
                ('resource_count', models.CharField(blank=True, db_column='resource_count', max_length=100, null=True)),
                ('inv_templatename', models.CharField(blank=True, db_column='Invoice_TemplateName', max_length=500, null=True)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('is_dragappt', models.BooleanField(db_column='is_dragappt', default=True)),
                ('is_empvalidate', models.BooleanField(db_column='is_empvalidate', default=True)),
                ('is_exclusive', models.BooleanField(null=True)),
                ('walkin_custid', models.IntegerField(blank=True, db_column='Walkin_Custid', null=True)),
                ('showallsitebooking', models.BooleanField(db_column='showallsitebooking', default=False)),
                ('ItemSite_Cityid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.City')),
                ('ItemSite_Countryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Country')),
                ('ItemSite_Stateid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.State')),
                ('Site_Groupid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.SiteGroup')),
            ],
            options={
                'db_table': 'Item_SiteList',
                'unique_together': {('itemsite_desc', 'itemsite_phone1', 'itemsite_email')},
            },
        ),
    ]
