# Generated by Django 3.0.7 on 2023-07-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0015_fmspw_emp_codeid'),
        ('cl_app', '0002_itemsitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsitelist',
            name='ItemSite_Userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw'),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='services',
            field=models.ManyToManyField(blank=True, to='cl_table.Stock'),
        ),
    ]
