# Generated by Django 3.0.7 on 2023-07-17 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cl_app', '0003_auto_20230717_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseTrmtReason',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rev_no', models.CharField(blank=True, db_column='Rev_No', max_length=50, null=True)),
                ('rev_desc', models.CharField(blank=True, db_column='Rev_Desc', max_length=50, null=True)),
                ('rev_remark', models.CharField(blank=True, db_column='Rev_Remark', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Is_active', default=True, null=True)),
            ],
            options={
                'db_table': 'Reverse_Trmt_Reason',
            },
        ),
        migrations.CreateModel(
            name='VoidReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_code', models.CharField(blank=True, db_column='Reason_Code', max_length=20, null=True)),
                ('reason_desc', models.CharField(blank=True, db_column='Reason_Desc', max_length=50, null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', default=True, null=True)),
            ],
            options={
                'db_table': 'Void_Reason',
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('current_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logged_inuser',
            },
        ),
    ]
