# Generated by Django 3.0.7 on 2023-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0004_loggedinuser_reversetrmtreason_voidreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentUsage',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('treatment_code', models.CharField(db_column='Treatment_Code', max_length=20)),
                ('item_code', models.CharField(db_column='Item_Code', max_length=20)),
                ('item_desc', models.CharField(db_column='Item_Desc', max_length=50)),
                ('qty', models.FloatField(db_column='Qty')),
                ('uom', models.CharField(db_column='UOM', max_length=20)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=50)),
                ('usage_status', models.CharField(blank=True, db_column='Usage_Status', max_length=20, null=True)),
                ('line_no', models.FloatField(blank=True, db_column='Line_No', null=True)),
                ('void_line_ref', models.CharField(blank=True, db_column='Void_Line_Ref', max_length=20, null=True)),
                ('usage_update', models.CharField(blank=True, db_column='Usage_Update', max_length=20, null=True)),
                ('sa_transacno', models.CharField(blank=True, db_column='SA_TRANSACNO', max_length=20, null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Treatment_Usage',
            },
        ),
    ]
