# Generated by Django 3.0.7 on 2023-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0005_treatmentusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMemo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('memo_no', models.CharField(blank=True, db_column='Memo_No', max_length=20, null=True)),
                ('item_code', models.CharField(blank=True, db_column='Item_Code', max_length=20, null=True)),
                ('item_name', models.CharField(blank=True, db_column='Item_Name', max_length=100, null=True)),
                ('date_out', models.DateTimeField(blank=True, db_column='Date_Out', null=True)),
                ('time_out', models.DateTimeField(auto_now=True, db_column='Time_Out', null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('uom', models.CharField(blank=True, db_column='UOM', max_length=10, null=True)),
                ('staff_code', models.CharField(blank=True, db_column='Staff_Code', max_length=20, null=True)),
                ('staff_name', models.CharField(blank=True, db_column='Staff_Name', max_length=100, null=True)),
                ('staff_barcode', models.CharField(blank=True, db_column='Staff_Barcode', max_length=20, null=True)),
                ('date_return', models.DateTimeField(blank=True, db_column='Date_Return', null=True)),
                ('time_return', models.DateTimeField(blank=True, db_column='Time_Return', null=True)),
                ('created_by', models.CharField(blank=True, db_column='Created_By', max_length=20, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('memo_remarks', models.CharField(blank=True, db_column='Memo_Remarks', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Usage_Memo',
            },
        ),
    ]
