# Generated by Django 3.0.7 on 2023-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0009_pricechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpTreatmentSession',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('treatment_parentcode', models.CharField(blank=True, db_column='Treatment_ParentCode', max_length=200, null=True)),
                ('session', models.IntegerField(blank=True, db_column='session', null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'TmpTreatmentSession',
            },
        ),
    ]
