# Generated by Django 3.0.7 on 2023-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0010_tmptreatmentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPromo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(blank=True, db_column='voucher_code', max_length=200, null=True)),
                ('voucher_desc', models.CharField(blank=True, db_column='voucher_desc', max_length=500, null=True)),
                ('sms_text', models.TextField(blank=True, db_column='sms_text', null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('isdiscount', models.BooleanField(db_column='isdiscount', default=False)),
                ('conditiontype1', models.CharField(blank=True, db_column='conditiontype1', max_length=20, null=True)),
                ('conditiontype2', models.CharField(blank=True, db_column='conditiontype2', max_length=20, null=True)),
            ],
            options={
                'db_table': 'VoucherPromo',
                'unique_together': {('price', 'isdiscount', 'conditiontype1', 'conditiontype2')},
            },
        ),
    ]
