# Generated by Django 3.0.7 on 2023-07-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0016_customer'),
        ('cl_app', '0012_smsprocesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpItemHelperSession',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('treatment_parentcode', models.CharField(blank=True, db_column='Treatment_ParentCode', max_length=200, null=True)),
                ('wp1', models.FloatField(blank=True, db_column='WP1', null=True)),
                ('session', models.FloatField(blank=True, db_column='Session', null=True)),
                ('helper_name', models.CharField(blank=True, db_column='Helper_Name', max_length=50, null=True)),
                ('helper_code', models.CharField(blank=True, db_column='Helper_Code', max_length=20, null=True)),
                ('sa_date', models.DateTimeField(blank=True, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=10, null=True)),
                ('helper_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
            ],
            options={
                'db_table': 'Tmp_Item_helperSession',
            },
        ),
    ]
