# Generated by Django 3.0.7 on 2023-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportmaster',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=255, null=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(db_column='Description', null=True)),
                ('pageid', models.CharField(db_column='PageID', max_length=255, null=True)),
                ('url', models.CharField(db_column='URL', max_length=255, null=True)),
                ('image', models.ImageField(db_column='Image', max_length=255, upload_to='img')),
                ('seq', models.IntegerField(db_column='Seq')),
                ('inactive', models.CharField(blank=True, db_column='InActive', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ReportMaster',
                'unique_together': {('name',)},
            },
        ),
    ]
