# Generated by Django 3.0.7 on 2023-07-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cl_table', '0112_invoicetemplate'),
        ('custom', '0071_posdiscquant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, db_column='Emp_name', max_length=600, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=100, null=True)),
                ('basicsalary', models.FloatField(blank=True, db_column='basicsalary', null=True)),
                ('hourlysalhour', models.FloatField(blank=True, db_column='hourlySalHour', null=True)),
                ('hourlysalrate', models.FloatField(blank=True, db_column='hourlySalRate', null=True)),
                ('firstovertimerate', models.FloatField(blank=True, db_column='firstOverTimeRate', null=True)),
                ('firstovertimehour', models.FloatField(blank=True, db_column='firstOverTimeHour', null=True)),
                ('secondovertimehour', models.FloatField(blank=True, db_column='secondOverTimeHour', null=True)),
                ('secondovertimerate', models.FloatField(blank=True, db_column='secondOverTimeRate', null=True)),
                ('tototpay', models.FloatField(blank=True, db_column='totOTPay', null=True)),
                ('totcommission', models.FloatField(blank=True, db_column='totCommission', null=True)),
                ('totallowance', models.FloatField(blank=True, db_column='totAllowance', null=True)),
                ('totdeduct', models.FloatField(blank=True, db_column='totDeduct', null=True)),
                ('addpay', models.FloatField(blank=True, db_column='AddPay', null=True)),
                ('netpay', models.FloatField(blank=True, db_column='netPay', null=True)),
                ('empcpfcont', models.FloatField(blank=True, db_column='empCPFCont', null=True)),
                ('dateofpay', models.DateField(blank=True, null=True)),
                ('salarystatus', models.CharField(blank=True, choices=[('New', 'New'), ('Open', 'Open'), ('Posted', 'Posted')], default='New', max_length=250, null=True)),
                ('salarymonth', models.CharField(blank=True, db_column='salarly_month', max_length=100, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('empid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
                ('modeofPayid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ModeOfPayment')),
            ],
            options={
                'db_table': 'Employee_Salary',
            },
        ),
    ]
