# Generated by Django 3.0.7 on 2023-07-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0071_posdiscquant'),
        ('clpayroll', '0003_deductionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentList',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('amount', models.FloatField(blank=True, db_column='amount', null=True)),
                ('emp_salaryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clpayroll.Employee_Salary')),
                ('type_nameid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.SalarySubTypeLookup')),
            ],
            options={
                'db_table': 'PaymentList',
            },
        ),
    ]
