# Generated by Django 3.0.7 on 2023-07-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cl_table', '0112_invoicetemplate'),
        ('cl_app', '0013_tmpitemhelpersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsultation_Hdr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_no', models.CharField(blank=True, db_column='DocNo', max_length=255, null=True)),
                ('cust_code', models.CharField(blank=True, db_column='CustCode', max_length=255, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('doc_date', models.DateTimeField(blank=True, db_column='DocDate', null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('consultant_code', models.CharField(blank=True, db_column='Consultant_Code', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('signature', models.ImageField(blank=True, db_column='Signature', null=True, upload_to='img')),
                ('cust_codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('emp_codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
                ('site_codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'WebConsultation_Hdr',
            },
        ),
    ]
