# Generated by Django 3.0.7 on 2023-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsultation_Dtl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_no', models.CharField(blank=True, db_column='DocNo', max_length=255, null=True)),
                ('question_number', models.CharField(blank=True, db_column='questionNumber', max_length=10, null=True)),
                ('answer', models.IntegerField(blank=True, db_column='answer', null=True)),
                ('answer_text', models.CharField(blank=True, db_column='answerText', max_length=200, null=True)),
                ('subquestion_number', models.CharField(blank=True, db_column='subquestionNumber', max_length=10, null=True)),
                ('image', models.ImageField(blank=True, db_column='image', max_length=255, null=True, upload_to='img')),
                ('pic_data1', models.TextField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, db_column='PageNumber', null=True)),
            ],
            options={
                'db_table': 'WebConsultation_Dtl',
            },
        ),
    ]
