# Generated by Django 3.0.7 on 2023-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0009_tnc_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNC_Header',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tncno', models.CharField(db_column='TNCNo', max_length=20)),
                ('cust_code', models.CharField(blank=True, db_column='CustCode', max_length=20, null=True)),
                ('consultant_code', models.CharField(blank=True, db_column='ConsultantCode', max_length=20, null=True)),
                ('signature1', models.ImageField(blank=True, db_column='Signature1', null=True, upload_to='img')),
                ('signature2', models.ImageField(blank=True, db_column='Signature2', null=True, upload_to='img')),
                ('sign_date', models.DateTimeField(blank=True, db_column='signDate', null=True)),
                ('site_code', models.CharField(blank=True, db_column='ItemSite_Code', max_length=20, null=True)),
            ],
            options={
                'db_table': 'TNC_Header',
                'unique_together': {('tncno',)},
            },
        ),
    ]
