# Generated by Django 3.0.7 on 2023-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0010_tnc_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNC_Detail',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tncno', models.CharField(blank=True, db_column='TNCNo', max_length=20, null=True)),
                ('receipt_date', models.DateTimeField(blank=True, db_column='ReceiptDate', null=True)),
                ('receiptno', models.CharField(blank=True, db_column='ReceiptNo', max_length=20, null=True)),
                ('package', models.CharField(blank=True, db_column='Package', max_length=80, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=18, null=True)),
                ('dt_lineno', models.IntegerField(blank=True, db_column='dt_LineNo', null=True)),
            ],
            options={
                'db_table': 'TNC_Detail',
            },
        ),
    ]
