# Generated by Django 3.0.7 on 2023-09-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0012_webconsultation_analysismaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconsultation_analysisresult',
            name='image',
            field=models.ImageField(blank=True, db_column='image', max_length=255, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='webconsultation_analysisresult',
            name='image1',
            field=models.ImageField(blank=True, db_column='image1', max_length=255, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='webconsultation_analysisresult',
            name='pic_data1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webconsultation_analysisresult',
            name='pic_data2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
