# Generated by Django 3.0.7 on 2023-07-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0003_auto_20230717_1210'),
        ('cl_table', '0015_fmspw_emp_codeid'),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_code', models.CharField(blank=True, db_column='Room_Code', max_length=10, null=True)),
                ('displayname', models.CharField(blank=True, db_column='DisplayName', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='Isactive', default=True, null=True)),
                ('equipment', models.CharField(blank=True, db_column='Equipment', max_length=50, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roomtype', models.CharField(blank=True, db_column='roomType', max_length=20, null=True)),
                ('equipmentpicturelocation', models.CharField(blank=True, db_column='equipmentPictureLocation', max_length=100, null=True)),
                ('Sequence_No', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Room_PIC', models.ImageField(null=True, upload_to='img')),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Combo_Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.FloatField(db_column='Unit_Price', null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('discount', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Isactive', models.BooleanField(default=True)),
                ('Site_Code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
                ('services', models.ManyToManyField(blank=True, to='cl_table.Stock')),
            ],
            options={
                'db_table': 'Combo_Services',
            },
        ),
    ]
