# Generated by Django 3.0.7 on 2023-07-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_combo_services_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundPoint',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('point', models.FloatField(blank=True, db_column='Point', null=True)),
                ('roundvalue', models.FloatField(blank=True, db_column='RoundValue', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Round_Point',
            },
        ),
        migrations.CreateModel(
            name='RoundSales',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sales', models.FloatField(blank=True, db_column='Sales', null=True)),
                ('roundvalue', models.FloatField(blank=True, db_column='RoundValue', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Round_Sales',
            },
        ),
    ]
