# Generated by Django 3.0.7 on 2023-07-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_roundpoint_roundsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolditemSetup',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hold_code', models.CharField(blank=True, db_column='Hold_code', max_length=50, null=True)),
                ('hold_desc', models.CharField(blank=True, db_column='Hold_Desc', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'HoldItem_Setup',
            },
        ),
        migrations.CreateModel(
            name='PaymentRemarks',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('r_code', models.CharField(blank=True, db_column='R_Code', max_length=20, null=True)),
                ('r_desc', models.CharField(blank=True, db_column='R_Desc', max_length=100, null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Payment_Remarks',
            },
        ),
    ]
