# Generated by Django 3.0.7 on 2023-07-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0016_customer'),
        ('cl_app', '0003_auto_20230717_1210'),
        ('custom', '0004_holditemsetup_paymentremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherRecord',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno', models.CharField(blank=True, max_length=20, null=True)),
                ('voucher_name', models.CharField(blank=True, db_column='Voucher_Name', max_length=100, null=True)),
                ('voucher_no', models.CharField(blank=True, db_column='Voucher_No', max_length=50, null=True)),
                ('value', models.FloatField(blank=True, db_column='Value', null=True)),
                ('sa_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_code', max_length=20, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=100, null=True)),
                ('percent', models.FloatField(blank=True, db_column='Percent', null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('issued_expiry_date', models.DateTimeField(blank=True, db_column='issued_Expiry_Date', null=True)),
                ('issued_staff', models.CharField(blank=True, db_column='issued_Staff', max_length=50, null=True)),
                ('onhold', models.CharField(blank=True, db_column='onHold', max_length=50, null=True)),
                ('paymenttype', models.CharField(blank=True, db_column='PaymentType', max_length=50, null=True)),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=100, null=True)),
                ('type_code', models.CharField(blank=True, max_length=50, null=True)),
                ('used', models.IntegerField(blank=True, db_column='Used', null=True)),
                ('ref_fullvoucherno', models.CharField(blank=True, db_column='Ref_FullVoucherNo', max_length=20, null=True)),
                ('ref_rangefrom', models.CharField(blank=True, db_column='Ref_RangeFrom', max_length=20, null=True)),
                ('ref_rangeto', models.CharField(blank=True, db_column='Ref_RangeTo', max_length=20, null=True)),
                ('site_allocate', models.CharField(blank=True, db_column='Site_Allocate', max_length=20, null=True)),
                ('dt_lineno', models.IntegerField(blank=True, db_column='dt_LineNo', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('isvalid', models.BooleanField(db_column='isValid', default=True)),
                ('isdiscount', models.BooleanField(db_column='isdiscount', default=False)),
                ('conditiontype1', models.CharField(blank=True, db_column='conditiontype1', max_length=20, null=True)),
                ('conditiontype2', models.CharField(blank=True, db_column='conditiontype2', max_length=20, null=True)),
                ('cust_codeid', models.ForeignKey(db_column='Cust_codeid', null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('site_codeid', models.ForeignKey(db_column='Site_Codeid', null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'Voucher_Record',
            },
        ),
    ]
