# Generated by Django 3.0.7 on 2023-07-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0040_depositaccount'),
        ('custom', '0007_pospackagedeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.DepositAccount'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='prepaid_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PrepaidAccount'),
        ),
    ]
