# Generated by Django 3.0.7 on 2023-07-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0085_exchangedtl'),
        ('custom', '0008_auto_20230717_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='exchange_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.ExchangeDtl'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='multistaff_ids',
            field=models.ManyToManyField(blank=True, related_name='multistaff', to='cl_table.Tmpmultistaff'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='pos_disc',
            field=models.ManyToManyField(blank=True, to='cl_table.PosDisc'),
        ),
    ]
