# Generated by Django 3.0.7 on 2023-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0010_smtpsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPricePolicy',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('item_class_code', models.CharField(db_column='Item_Class_Code', max_length=20)),
                ('cust_class_code', models.CharField(db_column='Cust_Class_Code', max_length=20)),
                ('disc_percent_limit', models.FloatField(blank=True, db_column='Disc_Percent_Limit', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Multi_Price_Policy',
            },
        ),
    ]
