# Generated by Django 3.0.7 on 2023-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0013_servicestaffchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='payModeChangeLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno', models.CharField(blank=True, max_length=20, null=True)),
                ('paytype', models.CharField(blank=True, max_length=30, null=True)),
                ('payamt', models.FloatField(blank=True, null=True)),
                ('newpaytype', models.CharField(blank=True, max_length=30, null=True)),
                ('newpayamt', models.FloatField(blank=True, null=True)),
                ('dt_lineno', models.IntegerField(null=True)),
                ('itemsite_code', models.CharField(db_column='itemsite_code', max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'payModeChangeLog',
            },
        ),
    ]
