# Generated by Django 3.0.7 on 2023-07-17 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0112_invoicetemplate'),
        ('custom', '0014_paymodechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='dateChangeLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_date', models.DateTimeField(blank=True, null=True)),
                ('new_date', models.DateTimeField(blank=True, null=True)),
                ('logtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('itemsite_code', models.CharField(db_column='itemsite_code', max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('haud_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PosHaud')),
            ],
            options={
                'db_table': 'dateChangeLog',
            },
        ),
    ]
