# Generated by Django 3.0.7 on 2023-07-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0112_invoicetemplate'),
        ('custom', '0017_timelogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(db_column='Project_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Project_Title', default='', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Project_Desc', default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Project_Status', default='', max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, db_column='Customer_Name', default='', max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='Contact_Person', default='', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, db_column='Contact_Number', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Project_Date', null=True)),
                ('sales_staff', models.CharField(blank=True, db_column='sales_staff', max_length=255, null=True)),
                ('admin_staff', models.CharField(blank=True, db_column='admin_staff', max_length=255, null=True)),
                ('operation_staff', models.CharField(blank=True, db_column='operation_staff', max_length=255, null=True)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
            ],
            options={
                'db_table': 'Project_List',
            },
        ),
    ]
