# Generated by Django 3.0.7 on 2023-07-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0112_invoicetemplate'),
        ('custom', '0019_activitymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationModel',
            fields=[
                ('id', models.AutoField(db_column='Quotation_ID', primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(blank=True, db_column='Quotation_Number', default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='Quotation_Project', default='', max_length=255, null=True)),
                ('company', models.CharField(blank=True, db_column='Quotation_Company', default='', max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='Quotation_ContactPerson', default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Quotation_Status', default='', max_length=255, null=True)),
                ('validity', models.CharField(blank=True, db_column='Quotation_Validity', default='', max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_column='Quotation_Terms', default='', max_length=255, null=True)),
                ('in_charge', models.CharField(blank=True, db_column='Quotation_InCharge', default='', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Quotation_Remarks', default='', max_length=255, null=True)),
                ('footer', models.CharField(blank=True, db_column='Quotation_Footer', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_column='Quotation_Date', null=True)),
                ('revision', models.IntegerField(blank=True, db_column='revision', null=True)),
                ('rev_quoteno', models.CharField(blank=True, db_column='rev_quoteno', max_length=255, null=True)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('fk_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel')),
            ],
            options={
                'db_table': 'Quotation_List',
            },
        ),
    ]
