# Generated by Django 3.0.7 on 2023-07-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0020_quotationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodel',
            name='fk_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel'),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='fk_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel'),
        ),
    ]
