# Generated by Django 3.0.7 on 2023-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0022_auto_20230717_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencytable',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('curr_code', models.CharField(blank=True, db_column='Curr_Code', max_length=3, null=True)),
                ('curr_name', models.CharField(blank=True, db_column='Curr_Name', max_length=255, null=True)),
                ('curr_rate', models.DecimalField(blank=True, db_column='Curr_Rate', decimal_places=1, max_digits=2, null=True)),
                ('curr_isactive', models.BooleanField(db_column='Curr_isactive', default=True)),
            ],
            options={
                'db_table': 'CurrencyTable',
            },
        ),
    ]
