# Generated by Django 3.0.7 on 2023-07-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0112_invoicetemplate'),
        ('custom', '0026_workorderinvoicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderModel',
            fields=[
                ('id', models.AutoField(db_column='DeliveryOrder_ID', primary_key=True, serialize=False)),
                ('do_number', models.CharField(blank=True, db_column='Do_Number', default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='Do_Project', default='', max_length=255, null=True)),
                ('company', models.CharField(blank=True, db_column='Do_Company', default='', max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='Do_ContactPerson', default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Do_Status', default='', max_length=255, null=True)),
                ('validity', models.CharField(blank=True, db_column='Do_Validity', default='', max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_column='Do_Terms', default='', max_length=255, null=True)),
                ('in_charge', models.CharField(blank=True, db_column='Do_InCharge', default='', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Do_Remarks', default='', max_length=255, null=True)),
                ('footer', models.CharField(blank=True, db_column='Do_Footer', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_column='Do_Date', null=True)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('fk_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel')),
                ('fk_workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.WorkOrderInvoiceModel')),
            ],
            options={
                'db_table': 'DeliveryOrder_List',
            },
        ),
    ]
