# Generated by Django 3.0.7 on 2023-07-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0032_poaddrmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationDetailModel',
            fields=[
                ('id', models.AutoField(db_column='Quotation_Detail_ID', primary_key=True, serialize=False)),
                ('q_shipcost', models.CharField(blank=True, db_column='Quotation_ShipCost', default='', max_length=255, null=True)),
                ('q_discount', models.CharField(blank=True, db_column='Quotation_Discount', default='', max_length=255, null=True)),
                ('q_discpercent', models.FloatField(default=0.0, null=True)),
                ('q_taxes', models.CharField(blank=True, db_column='Quotation_Taxes', default='', max_length=255, null=True)),
                ('q_total', models.CharField(blank=True, db_column='Quotation_Total', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_quotation', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel')),
            ],
            options={
                'db_table': 'Quotation_Detail',
            },
        ),
    ]
