# Generated by Django 3.0.7 on 2023-07-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0037_workorderinvoicedetailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderDetailModel',
            fields=[
                ('id', models.AutoField(db_column='Do_Detail_ID', primary_key=True, serialize=False)),
                ('q_shipcost', models.CharField(blank=True, db_column='Do_ShipCost', default='', max_length=255, null=True)),
                ('q_discount', models.CharField(blank=True, db_column='Do_Discount', default='', max_length=255, null=True)),
                ('q_taxes', models.CharField(blank=True, db_column='Do_Taxes', default='', max_length=255, null=True)),
                ('q_total', models.CharField(blank=True, db_column='Do_Total', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_deliveryorder', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.DeliveryOrderModel')),
            ],
            options={
                'db_table': 'DeliveryOrder_Detail',
            },
        ),
    ]
