# Generated by Django 3.0.7 on 2023-07-17 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0040_quotationitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='quotationitem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationItemModel'),
        ),
    ]
