# Generated by Django 3.0.7 on 2023-07-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0043_workorderinvoiceitemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderItemModel',
            fields=[
                ('id', models.AutoField(db_column='Do_Item_ID', primary_key=True, serialize=False)),
                ('quotation_quantity', models.CharField(blank=True, db_column='Do_Item_Quantity', default='', max_length=255, null=True)),
                ('quotation_unitprice', models.CharField(blank=True, db_column='Do_Item_UnitPrice', default='', max_length=255, null=True)),
                ('quotation_itemremarks', models.CharField(blank=True, db_column='Do_Item_Remarks', default='', max_length=255, null=True)),
                ('quotation_itemcode', models.CharField(blank=True, db_column='Do_Item_Code', default='', max_length=255, null=True)),
                ('quotation_itemdesc', models.CharField(blank=True, db_column='Do_Item_Desc', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_deliveryorder', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.DeliveryOrderModel')),
            ],
            options={
                'db_table': 'DeliveryOrder_Item',
            },
        ),
    ]
