# Generated by Django 3.0.7 on 2023-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0046_dropdownmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='POApprovalModel',
            fields=[
                ('POAPP_ID', models.AutoField(db_column='POAPP_ID', primary_key=True, serialize=False)),
                ('PO_No', models.CharField(blank=True, db_column='PO_No', default='', max_length=255, null=True)),
                ('GRN_No', models.CharField(blank=True, db_column='GRN_No', default='', max_length=255, null=True)),
                ('ITEMSITE_CODE', models.CharField(blank=True, db_column='ITEMSITE_CODE', default='', max_length=255, null=True)),
                ('STATUS', models.CharField(blank=True, db_column='STATUS', default='', max_length=255, null=True)),
                ('POAPP_ITEMCODE', models.IntegerField(blank=True, db_column='POAPP_ITEMCODE', null=True)),
                ('POAPP_ITEMDESC', models.CharField(blank=True, db_column='POAPP_ITEMDESC', default='', max_length=255, null=True)),
                ('POAPP_ITEMPRICE', models.FloatField(blank=True, db_column='POAPP_ITEMPRICE', null=True)),
                ('POAPP_QTY', models.IntegerField(blank=True, db_column='POAPP_QTY', null=True)),
                ('POAPP_TTLQTY', models.IntegerField(blank=True, db_column='POAPP_TTLQTY', null=True)),
                ('POAPP_AMT', models.FloatField(blank=True, db_column='POAPP_AMT', null=True)),
            ],
            options={
                'db_table': 'PO_Approval',
            },
        ),
    ]
