# Generated by Django 3.0.7 on 2023-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0047_poapprovalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOModel',
            fields=[
                ('DO_ID', models.AutoField(db_column='DO_ID', primary_key=True, serialize=False)),
                ('DO_NO', models.CharField(blank=True, db_column='DO_NO', default='', max_length=255, null=True)),
                ('ItemSite_Code', models.CharField(blank=True, db_column='ItemSite_Code', default='', max_length=255, null=True)),
                ('SUPP_Code', models.CharField(blank=True, db_column='SUPP_Code', default='', max_length=255, null=True)),
                ('DO_REF', models.CharField(blank=True, db_column='DO_REF', default='', max_length=255, null=True)),
                ('DO_User', models.CharField(blank=True, db_column='DO_User', default='', max_length=255, null=True)),
                ('DO_DATE', models.DateTimeField(db_column='DO_DATE', null=True)),
                ('DO_STATUS', models.CharField(blank=True, db_column='DO_STATUS', default='', max_length=255, null=True)),
                ('DO_TTQTY', models.FloatField(blank=True, db_column='DO_TTQTY', null=True)),
                ('DO_TTFOC', models.FloatField(blank=True, db_column='DO_TTFOC', null=True)),
                ('DO_TTDISC', models.FloatField(blank=True, db_column='DO_TTDISC', null=True)),
                ('DO_TTAMT', models.FloatField(blank=True, db_column='DO_TTAMT', null=True)),
                ('DO_ATTN', models.CharField(blank=True, db_column='DO_ATTN', default='', max_length=255, null=True)),
                ('DO_REMK1', models.CharField(blank=True, db_column='DO_REMK1', default='', max_length=255, null=True)),
                ('DO_REMK2', models.CharField(blank=True, db_column='DO_REMK2', default='', max_length=255, null=True)),
                ('DO_BNAME', models.CharField(blank=True, db_column='DO_BNAME', default='', max_length=255, null=True)),
                ('DO_BADDR1', models.CharField(blank=True, db_column='DO_BADDR1', default='', max_length=255, null=True)),
                ('DO_BADDR2', models.CharField(blank=True, db_column='DO_BADDR2', default='', max_length=255, null=True)),
                ('DO_BADDR3', models.CharField(blank=True, db_column='DO_BADDR3', default='', max_length=255, null=True)),
                ('DO_BPOSTCODE', models.CharField(blank=True, db_column='DO_BPOSTCODE', default='', max_length=255, null=True)),
                ('DO_BSTATE', models.CharField(blank=True, db_column='DO_BSTATE', default='', max_length=255, null=True)),
                ('DO_BCITY', models.CharField(blank=True, db_column='DO_BCITY', default='', max_length=255, null=True)),
                ('DO_BCOUNTRY', models.CharField(blank=True, db_column='DO_BCOUNTRY', default='', max_length=255, null=True)),
                ('DO_DADDR1', models.CharField(blank=True, db_column='DO_DADDR1', default='', max_length=255, null=True)),
                ('DO_DADDR2', models.CharField(blank=True, db_column='DO_DADDR2', default='', max_length=255, null=True)),
                ('DO_DADDR3', models.CharField(blank=True, db_column='DO_DADDR3', default='', max_length=255, null=True)),
                ('DO_DPOSTCODE', models.CharField(blank=True, db_column='DO_DPOSTCODE', default='', max_length=255, null=True)),
                ('DO_DSTATE', models.CharField(blank=True, db_column='DO_DSTATE', default='', max_length=255, null=True)),
                ('DO_DCITY', models.CharField(blank=True, db_column='DO_DCITY', default='', max_length=255, null=True)),
                ('DO_DCOUNTRY', models.CharField(blank=True, db_column='DO_DCOUNTRY', default='', max_length=255, null=True)),
                ('DO_CANCELQTY', models.FloatField(blank=True, db_column='DO_CANCELQTY', null=True)),
                ('DO_RECSTATUS', models.CharField(blank=True, db_column='DO_RECSTATUS', default='', max_length=255, null=True)),
                ('DO_RECEXPECT', models.DateTimeField(db_column='DO_RECEXPECT', null=True)),
                ('DO_RECTTL', models.FloatField(blank=True, db_column='DO_RECTTL', null=True)),
                ('DO_TIME', models.DateTimeField(db_column='DO_TIME', null=True)),
                ('PO_NO', models.CharField(blank=True, db_column='PO_NO', default='', max_length=255, null=True)),
                ('contactPerson', models.CharField(blank=True, db_column='contactPerson', default='', max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_column='terms', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'DO',
            },
        ),
    ]
