# Generated by Django 3.0.7 on 2023-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0048_domodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DODetailModel',
            fields=[
                ('DO_ID', models.AutoField(db_column='DO_ID', primary_key=True, serialize=False)),
                ('ITEMSITE_CODE', models.CharField(blank=True, db_column='ITEMSITE_CODE', default='', max_length=255, null=True)),
                ('STATUS', models.CharField(blank=True, db_column='STATUS', default='', max_length=255, null=True)),
                ('DOD_ITEMCODE', models.CharField(blank=True, db_column='DOD_ITEMCODE', default='', max_length=255, null=True)),
                ('DOD_ITEMDESC', models.CharField(blank=True, db_column='DOD_ITEMDESC', default='', max_length=255, null=True)),
                ('DOD_ITEMPRICE', models.FloatField(blank=True, db_column='DOD_ITEMPRICE', null=True)),
                ('DOD_QTY', models.IntegerField(blank=True, db_column='DOD_QTY', null=True)),
                ('DOD_FOCQTY', models.IntegerField(blank=True, db_column='DOD_FOCQTY', null=True)),
                ('DOD_TTLQTY', models.IntegerField(blank=True, db_column='DOD_TTLQTY', null=True)),
                ('DOD_PRICE', models.FloatField(blank=True, db_column='DOD_PRICE', null=True)),
                ('DOD_DISCPER', models.FloatField(blank=True, db_column='DOD_DISCPER', null=True)),
                ('DOD_DISCAMT', models.FloatField(blank=True, db_column='DOD_DISCAMT', null=True)),
                ('DOD_AMT', models.FloatField(blank=True, db_column='DOD_AMT', null=True)),
                ('DOD_RECQTY', models.IntegerField(blank=True, db_column='DOD_RECQTY', null=True)),
                ('DOD_CANCELQTY', models.IntegerField(blank=True, db_column='DOD_CANCELQTY', null=True)),
                ('DOD_OUTQTY', models.IntegerField(blank=True, db_column='DOD_OUTQTY', null=True)),
                ('DOD_DATE', models.DateTimeField(db_column='DOD_DATE', null=True)),
                ('DOD_TIME', models.DateTimeField(db_column='DOD_TIME', null=True)),
                ('BrandCode', models.CharField(blank=True, db_column='BrandCode', default='', max_length=255, null=True)),
                ('BrandName', models.CharField(blank=True, db_column='BrandName', default='', max_length=255, null=True)),
                ('LineNumber', models.IntegerField(blank=True, db_column='LineNumber', null=True)),
                ('DO_No', models.CharField(blank=True, db_column='DO_No', default='', max_length=255, null=True)),
                ('PostStatus', models.IntegerField(blank=True, db_column='PostStatus', null=True)),
            ],
            options={
                'db_table': 'DO_DETAIL',
            },
        ),
    ]
