# Generated by Django 3.0.7 on 2023-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0050_authorisemodel_employeelistmodel_itembatchmodel_itembrandmodel_itemdeptmodel_itemrangemodel_itemuomp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSupplyModel',
            fields=[
                ('SPLY_ID', models.AutoField(db_column='SPLY_ID', primary_key=True, serialize=False)),
                ('SPLY_CODE', models.CharField(blank=True, db_column='SPLY_CODE', default='', max_length=255, null=True)),
                ('SUPPLYDESC', models.CharField(blank=True, db_column='SUPPLYDESC', default='', max_length=255, null=True)),
                ('SPLY_DATE', models.DateTimeField(db_column='SPLY_DATE', null=True)),
                ('SPLY_ATTN', models.CharField(blank=True, db_column='SPLY_ATTN', default='', max_length=255, null=True)),
                ('SPLY_IC', models.CharField(blank=True, db_column='SPLY_IC', default='', max_length=255, null=True)),
                ('SPLY_TYPE', models.CharField(blank=True, db_column='SPLY_TYPE', default='', max_length=255, null=True)),
                ('SPLY_ADDR1', models.CharField(blank=True, db_column='SPLY_ADDR1', default='', max_length=255, null=True)),
                ('SPLY_ADDR2', models.CharField(blank=True, db_column='SPLY_ADDR2', default='', max_length=255, null=True)),
                ('SPLY_ADDR3', models.CharField(blank=True, db_column='SPLY_ADDR3', default='', max_length=255, null=True)),
                ('SPLY_POSCD', models.CharField(blank=True, db_column='SPLY_POSCD', default='', max_length=255, null=True)),
                ('SPLY_STATE', models.CharField(blank=True, db_column='SPLY_STATE', default='', max_length=255, null=True)),
                ('SPLY_CITY', models.CharField(blank=True, db_column='SPLY_CITY', default='', max_length=255, null=True)),
                ('SPLY_CNTRY', models.CharField(blank=True, db_column='SPLY_CNTRY', default='', max_length=255, null=True)),
                ('SPLYMADDR1', models.CharField(blank=True, db_column='SPLYMADDR1', default='', max_length=255, null=True)),
                ('SPLYMADDR2', models.CharField(blank=True, db_column='SPLYMADDR2', default='', max_length=255, null=True)),
                ('SPLYMADDR3', models.CharField(blank=True, db_column='SPLYMADDR3', default='', max_length=255, null=True)),
                ('SPLYMPOSCD', models.CharField(blank=True, db_column='SPLYMPOSCD', default='', max_length=255, null=True)),
                ('SPLYMSTATE', models.CharField(blank=True, db_column='SPLYMSTATE', default='', max_length=255, null=True)),
                ('SPLYMCITY', models.CharField(blank=True, db_column='SPLYMCITY', default='', max_length=255, null=True)),
                ('SPLYMCNTRY', models.CharField(blank=True, db_column='SPLYMCNTRY', default='', max_length=255, null=True)),
                ('SPLY_TELNO', models.CharField(blank=True, db_column='SPLY_TELNO', default='', max_length=255, null=True)),
                ('SPLY_FAXNO', models.CharField(blank=True, db_column='SPLY_FAXNO', default='', max_length=255, null=True)),
                ('SPLY_REMK1', models.CharField(blank=True, db_column='SPLY_REMK1', default='', max_length=255, null=True)),
                ('SPLY_REMK2', models.CharField(blank=True, db_column='SPLY_REMK2', default='', max_length=255, null=True)),
                ('SPLY_REMK3', models.CharField(blank=True, db_column='SPLY_REMK3', default='', max_length=255, null=True)),
                ('SPLY_TERM', models.CharField(blank=True, db_column='SPLY_TERM', default='', max_length=255, null=True)),
                ('SPLY_LIMIT', models.IntegerField(blank=True, db_column='SPLY_LIMIT', null=True)),
                ('SPLY_BAL', models.IntegerField(blank=True, db_column='SPLY_BAL', null=True)),
                ('SPLYACTIVE', models.IntegerField(blank=True, db_column='SPLYACTIVE', null=True)),
                ('SPLY_COMM', models.IntegerField(blank=True, db_column='SPLY_COMM', null=True)),
                ('FIRST_NAME', models.CharField(blank=True, db_column='FIRST_NAME', default='', max_length=255, null=True)),
                ('NETSEQ', models.CharField(blank=True, db_column='NETSEQ', default='', max_length=255, null=True)),
                ('CREATE_USER', models.CharField(blank=True, db_column='CREATE_USER', default='', max_length=255, null=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE', null=True)),
                ('numberOfTotalPOs', models.CharField(blank=True, db_column='numberOfTotalPOs', default='', max_length=255, null=True)),
                ('numberOfOpenPOs', models.CharField(blank=True, db_column='numberOfOpenPOs', default='', max_length=255, null=True)),
                ('accountNumber', models.CharField(blank=True, db_column='accountNumber', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Item_Supply',
            },
        ),
    ]
