# Generated by Django 3.0.7 on 2023-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0053_movhdrmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovDtlModel',
            fields=[
                ('DOC_ID', models.AutoField(db_column='DOC_ID', primary_key=True, serialize=False)),
                ('DOC_NO', models.CharField(blank=True, db_column='DOC_NO', default='', max_length=255, null=True)),
                ('MOV_CODE', models.CharField(blank=True, db_column='MOV_CODE', default='', max_length=255, null=True)),
                ('MOV_TYPE', models.CharField(blank=True, db_column='MOV_TYPE', default='', max_length=255, null=True)),
                ('DOC_LINENO', models.FloatField(blank=True, db_column='DOC_LINENO', null=True)),
                ('DOC_DATE', models.DateTimeField(auto_now_add=True, db_column='DOC_DATE', null=True)),
                ('GRN_NO', models.CharField(blank=True, db_column='GRN_NO', default='', max_length=255, null=True)),
                ('REF_NO', models.CharField(blank=True, db_column='REF_NO', default='', max_length=255, null=True)),
                ('ITEMCODE', models.CharField(blank=True, db_column='ITEMCODE', default='', max_length=255, null=True)),
                ('ITEMDESC', models.CharField(blank=True, db_column='ITEMDESC', default='', max_length=255, null=True)),
                ('ITEMPRICE', models.FloatField(blank=True, db_column='ITEMPRICE', null=True)),
                ('DOC_UOMTYPE', models.CharField(blank=True, db_column='DOC_UOMTYPE', default='', max_length=255, null=True)),
                ('DOC_UOMQTY', models.FloatField(blank=True, db_column='DOC_UOMQTY', null=True)),
                ('DOC_QTY', models.FloatField(blank=True, db_column='DOC_QTY', null=True)),
                ('DOC_FOCQTY', models.FloatField(blank=True, db_column='DOC_FOCQTY', null=True)),
                ('DOC_TTLQTY', models.FloatField(blank=True, db_column='DOC_TTLQTY', null=True)),
                ('DOC_PRICE', models.FloatField(blank=True, db_column='DOC_PRICE', null=True)),
                ('DOC_MDISC', models.CharField(blank=True, db_column='DOC_MDISC', default='', max_length=255, null=True)),
                ('DOC_PDISC', models.FloatField(blank=True, db_column='DOC_PDISC', null=True)),
                ('DOC_DISC', models.FloatField(blank=True, db_column='DOC_DISC', null=True)),
                ('DOC_AMT', models.FloatField(blank=True, db_column='DOC_AMT', null=True)),
                ('REC_QTY1', models.FloatField(blank=True, db_column='REC_QTY1', null=True)),
                ('REC_QTY2', models.FloatField(blank=True, db_column='REC_QTY2', null=True)),
                ('REC_QTY3', models.FloatField(blank=True, db_column='REC_QTY3', null=True)),
                ('REC_QTY5', models.FloatField(blank=True, db_column='REC_QTY5', null=True)),
                ('REC_TTL', models.FloatField(blank=True, db_column='REC_TTL', null=True)),
                ('POSTED_QTY', models.FloatField(blank=True, db_column='POSTED_QTY', null=True)),
                ('CANCEL_QTY', models.FloatField(blank=True, db_column='CANCEL_QTY', null=True)),
                ('ORD_MEMO1', models.CharField(blank=True, db_column='ORD_MEMO1', default='', max_length=255, null=True)),
                ('ORD_MEMO2', models.CharField(blank=True, db_column='ORD_MEMO2', default='', max_length=255, null=True)),
                ('ORD_MEMO3', models.CharField(blank=True, db_column='ORD_MEMO3', default='', max_length=255, null=True)),
                ('ORD_MEMO4', models.CharField(blank=True, db_column='ORD_MEMO4', default='', max_length=255, null=True)),
                ('CREATE_USER', models.CharField(blank=True, db_column='CREATE_USER', default='', max_length=255, null=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE', null=True)),
                ('DOC_UOM', models.CharField(blank=True, db_column='DOC_UOM', default='', max_length=255, null=True)),
                ('DOC_EXPDATE', models.DateTimeField(auto_now=True, db_column='DOC_EXPDATE', null=True)),
                ('DOC_BATCH_NO', models.CharField(blank=True, db_column='DOC_BATCH_NO', default='', max_length=255, null=True)),
                ('PHY_NO', models.CharField(blank=True, db_column='PHY_NO', default='', max_length=255, null=True)),
                ('itm_Brand', models.CharField(blank=True, db_column='itm_Brand', default='', max_length=255, null=True)),
                ('itm_Range', models.CharField(blank=True, db_column='itm_Range', default='', max_length=255, null=True)),
                ('Stk_Adj_Reason_Code', models.CharField(blank=True, db_column='Stk_Adj_Reason_Code', default='', max_length=255, null=True)),
                ('ITEM_REMARK', models.CharField(blank=True, db_column='ITEM_REMARK', default='', max_length=255, null=True)),
                ('DOCUOMDesc', models.CharField(blank=True, db_column='DOCUOMDesc', default='', max_length=255, null=True)),
                ('itmBrandDesc', models.CharField(blank=True, db_column='itmBrandDesc', default='', max_length=255, null=True)),
                ('itmRangeDesc', models.CharField(blank=True, db_column='itmRangeDesc', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Stk_MovDoc_Dtl',
            },
        ),
    ]
