# Generated by Django 3.0.7 on 2023-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0054_movdtlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHYHdrModel',
            fields=[
                ('PHY_ID', models.AutoField(db_column='PHY_ID', primary_key=True, serialize=False)),
                ('PHY_NO', models.CharField(blank=True, db_column='PHY_NO', default='', max_length=255, null=True)),
                ('STORE_NO', models.CharField(blank=True, db_column='STORE_NO', default='', max_length=255, null=True)),
                ('PHY_REF', models.CharField(blank=True, db_column='PHY_REF', default='', max_length=255, null=True)),
                ('PHY_REMK1', models.CharField(blank=True, db_column='PHY_REMK1', default='', max_length=255, null=True)),
                ('PHY_DATE', models.DateTimeField(auto_now_add=True, db_column='PHY_DATE', null=True)),
                ('POST_DATE', models.DateTimeField(auto_now_add=True, db_column='POST_DATE', null=True)),
                ('STAFF_NO', models.CharField(blank=True, db_column='STAFF_NO', default='', max_length=255, null=True)),
                ('STAFF_NAME', models.CharField(blank=True, db_column='STAFF_NAME', default='', max_length=255, null=True)),
                ('PHY_STATUS', models.FloatField(blank=True, db_column='PHY_STATUS', null=True)),
                ('PHY_LINES', models.FloatField(blank=True, db_column='PHY_LINES', null=True)),
                ('PHY_TTLQTY', models.FloatField(blank=True, db_column='PHY_TTLQTY', null=True)),
                ('PHY_TTLAMT', models.FloatField(blank=True, db_column='PHY_TTLAMT', null=True)),
                ('PHY_COUNTQTY', models.FloatField(blank=True, db_column='PHY_COUNTQTY', null=True)),
            ],
            options={
                'db_table': 'STK_PHYHdr',
            },
        ),
    ]
