# Generated by Django 3.0.7 on 2023-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0055_phyhdrmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHYDtlModel',
            fields=[
                ('PHY_ID', models.AutoField(db_column='PHY_ID', primary_key=True, serialize=False)),
                ('PHY_NO', models.CharField(blank=True, db_column='PHY_NO', default='', max_length=255, null=True)),
                ('STORE_NO', models.CharField(blank=True, db_column='STORE_NO', default='', max_length=255, null=True)),
                ('PHY_LINENO', models.FloatField(blank=True, db_column='PHY_LINENO', null=True)),
                ('PHY_DATE', models.DateTimeField(auto_now_add=True, db_column='PHY_DATE', null=True)),
                ('STAFF_NO', models.CharField(blank=True, db_column='STAFF_NO', default='', max_length=255, null=True)),
                ('STATUS', models.FloatField(blank=True, db_column='STATUS', null=True)),
                ('ITEMCODE', models.CharField(blank=True, db_column='ITEMCODE', default='', max_length=255, null=True)),
                ('ITEMDESC', models.CharField(blank=True, db_column='ITEMDESC', default='', max_length=255, null=True)),
                ('PHY_REMARK', models.CharField(blank=True, db_column='PHY_REMARK', default='', max_length=255, null=True)),
                ('PHY_UOM', models.CharField(blank=True, db_column='PHY_UOM', default='', max_length=255, null=True)),
                ('PHY_UOMTYPE', models.CharField(blank=True, db_column='PHY_UOMTYPE', default='', max_length=255, null=True)),
                ('PHY_UOMQTY', models.FloatField(blank=True, db_column='PHY_UOMQTY', null=True)),
                ('PHY_QTY', models.FloatField(blank=True, db_column='PHY_QTY', null=True)),
                ('PHY_TTLQTY', models.FloatField(blank=True, db_column='PHY_TTLQTY', null=True)),
                ('PHY_COUNTQTY', models.FloatField(blank=True, db_column='PHY_COUNTQTY', null=True)),
                ('PHY_VARIANCE', models.FloatField(blank=True, db_column='PHY_VARIANCE', null=True)),
                ('PHY_AMT', models.FloatField(blank=True, db_column='PHY_AMT', null=True)),
                ('PHY_COST', models.FloatField(blank=True, db_column='PHY_COST', null=True)),
                ('PHY_UCOST', models.FloatField(blank=True, db_column='PHY_UCOST', null=True)),
            ],
            options={
                'db_table': 'STK_PHYdtl',
            },
        ),
    ]
