# Generated by Django 3.0.7 on 2023-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0056_phydtlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogModel',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Log_Type', models.CharField(blank=True, db_column='Log_Type', default='', max_length=255, null=True)),
                ('Log_DateTime', models.DateTimeField(auto_now_add=True, db_column='Log_DateTime', null=True)),
                ('Log_User', models.CharField(blank=True, db_column='Log_User', default='', max_length=255, null=True)),
                ('Log_Process', models.CharField(blank=True, db_column='Log_Process', default='', max_length=255, null=True)),
                ('Log_Message', models.CharField(blank=True, db_column='Log_Message', default='', max_length=255, null=True)),
                ('Log_Site_Code', models.CharField(blank=True, db_column='Log_Site_Code', default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': 'SystemLog',
                'managed': False,
            },
        ),
    ]
