# Generated by Django 3.0.7 on 2023-07-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0059_supplycontactinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNoModel',
            fields=[
                ('id', models.AutoField(db_column='Control_id', primary_key=True, serialize=False)),
                ('control_prefix', models.CharField(blank=True, db_column='control_prefix', default='', max_length=255, null=True)),
                ('control_description', models.CharField(blank=True, db_column='control_description', default='', max_length=255, null=True)),
                ('control_no', models.CharField(blank=True, db_column='control_no', default='', max_length=255, null=True)),
                ('Site_Code', models.CharField(blank=True, db_column='Site_Code', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Control_No',
                'managed': False,
            },
        ),
    ]
