# Generated by Django 3.0.7 on 2023-07-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0060_controlnomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('1', 'year'), ('2', 'month'), ('3', 'week')], default=None, max_length=20)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('min_value', models.FloatField(db_column='Target min')),
                ('max_value', models.FloatField(db_column='Target max')),
                ('commission', models.IntegerField(blank=True, db_column='commission', null=True)),
                ('ispercent', models.BooleanField()),
                ('incentive', models.FloatField(db_column='incentive', null=True)),
                ('incentive_ispercent', models.BooleanField()),
                ('commission_type', models.BooleanField()),
                ('brand_comm_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='range_brand', to='custom.ItemBrandModel')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.ItemBrandModel')),
                ('department_comm_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='range_dept', to='custom.ItemDeptModel')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_department', to='custom.ItemDeptModel')),
                ('employe_level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.EmpLevel')),
                ('range_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.ItemRangeModel')),
                ('rangee_comm_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='range_commission', to='custom.ItemRangeModel')),
            ],
            options={
                'db_table': 'Commission_profile',
            },
        ),
    ]
