# Generated by Django 3.0.7 on 2023-07-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0061_commissionprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('from_date_comm', models.DateField(null=True)),
                ('to_date_comm', models.DateField(null=True)),
                ('min_value_comm', models.FloatField(blank=True, db_column='Target min comm', null=True)),
                ('max_value_comm', models.FloatField(blank=True, db_column='Target max comm', null=True)),
                ('commission_comm', models.IntegerField(blank=True, db_column='commission comm', null=True)),
                ('ispercent_comm', models.BooleanField(default=False)),
                ('incentive_comm', models.FloatField(blank=True, db_column='incentive comm', null=True)),
                ('incentive_ispercent_comm', models.BooleanField(default=False)),
                ('comm_Profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.CommissionProfile')),
                ('employe_level_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.EmpLevel')),
            ],
            options={
                'db_table': 'Comm_target',
            },
        ),
        migrations.CreateModel(
            name='CommDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('gst', models.FloatField(blank=True, db_column='GST', null=True)),
                ('gst_ispercent', models.BooleanField(default=False)),
                ('bank_changes', models.FloatField(blank=True, db_column='Bank changes', null=True)),
                ('bc_ispercent', models.BooleanField(default=False)),
                ('emi', models.FloatField(blank=True, db_column='EMI', null=True)),
                ('emi_ispercent', models.BooleanField(default=False)),
                ('comm_Profilede_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.CommissionProfile')),
                ('employe_level_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.EmpLevel')),
            ],
            options={
                'db_table': 'Comm_deduction',
            },
        ),
    ]
