# Generated by Django 3.0.7 on 2023-07-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0062_commdeduction_commtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySubTypeLookup',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=40)),
                ('accountcode', models.CharField(max_length=10)),
                ('showinallowance', models.BooleanField(default=False)),
                ('showindeduction', models.BooleanField(default=False)),
                ('showinpayment', models.BooleanField(default=False)),
                ('isactive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SalarySubTypeLookup',
            },
        ),
    ]
