# Generated by Django 3.0.7 on 2023-07-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0064_modeofpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrdersign',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('deliveryorder_no', models.CharField(blank=True, db_column='DeliveryOrder_No', max_length=255, null=True)),
                ('do_sig', models.ImageField(blank=True, db_column='DO_Sig', null=True, upload_to='img')),
                ('do_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.DeliveryOrderModel')),
            ],
            options={
                'db_table': 'DeliveryOrdersign',
            },
        ),
    ]
