# Generated by Django 3.0.7 on 2023-07-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0065_deliveryordersign'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotationsign',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(blank=True, db_column='Quotation_Number', default='', max_length=255, null=True)),
                ('quo_sig', models.ImageField(blank=True, db_column='quo_sig', null=True, upload_to='img')),
                ('fk_quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel')),
            ],
            options={
                'db_table': 'quotationsign',
            },
        ),
    ]
