# Generated by Django 3.0.7 on 2023-07-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0112_invoicetemplate'),
        ('custom', '0068_equipmentusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUsageItemModel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quotation_quantity', models.CharField(blank=True, db_column='Item_Quantity', default='', max_length=255, null=True)),
                ('quotation_unitprice', models.CharField(blank=True, db_column='Item_UnitPrice', default='', max_length=255, null=True)),
                ('quotation_itemremarks', models.CharField(blank=True, db_column='Item_Remarks', default='', max_length=255, null=True)),
                ('quotation_itemcode', models.CharField(blank=True, db_column='Item_Code', default='', max_length=255, null=True)),
                ('quotation_itemdesc', models.CharField(blank=True, db_column='Item_Desc', default='', max_length=255, null=True)),
                ('item_uom', models.CharField(blank=True, db_column='Item_UOM', max_length=600, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('item_div', models.CharField(blank=True, db_column='Item_Div', max_length=20, null=True)),
                ('Item_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock')),
                ('fk_equipment', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.EquipmentUsage')),
            ],
            options={
                'db_table': 'EquipmentUsage_Item',
            },
        ),
    ]
