# Generated by Django 3.0.7 on 2023-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0069_equipmentusageitemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDropdownModel',
            fields=[
                ('id', models.AutoField(db_column='Dropdown_ID', primary_key=True, serialize=False)),
                ('dropdown_item', models.CharField(blank=True, db_column='Dropdown_Item', default='', max_length=255, null=True)),
                ('dropdown_desc', models.CharField(blank=True, db_column='Dropdown_Desc', default='', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'EquipmentDropdownModel',
            },
        ),
    ]
