# Generated by Django 3.0.7 on 2023-09-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0071_posdiscquant'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='prepaid_deposit',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
