# Generated by Django 3.0.7 on 2023-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0073_auto_20230916_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsettings',
            name='email_use_ssl',
            field=models.BooleanField(db_column='EMAIL_USE_SSL', default=False),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='email_use_tls',
            field=models.BooleanField(db_column='EMAIL_USE_TLS', default=True),
        ),
        migrations.AlterUniqueTogether(
            name='smtpsettings',
            unique_together={('email_subject', 'site_code')},
        ),
    ]
